import type { CivicEntity } from "../types.ts";

// Cornell / Ithaca civic context. Offices and places describe what they are;
// officeholder names, photos and party labels are omitted until checked against
// an official source. Proposals, briefs and questions are marked as samples.
// Coordinates are approximate map positions, not surveyed addresses.
const communityId = "ithaca";
const entity = (
  e: Omit<CivicEntity, "communityId" | "related" | "topics" | "sample"> &
    Partial<Pick<CivicEntity, "related" | "topics" | "sample">>,
): CivicEntity => ({ communityId, related: [], topics: [], sample: false, ...e });
const city = "https://www.cityofithacany.gov/";
const county = "https://www.tompkinscountyny.gov/";
const cornell = "https://www.cornell.edu/";
const tcat = "https://tcatbus.com/";

export const cornellEntities: CivicEntity[] = [
  // Issues keep their original IDs so existing posts, follows and priorities apply.
  entity({
    id: "housing",
    kind: "issue",
    name: "Housing affordability",
    subtitle: "Ithaca · Housing",
    summary: "Homes, rents and how neighborhoods near campus grow.",
    scope: "local",
    related: ["ith-collegetown", "q-ith-collegetown-housing", "ith-collegetown-homes", "ith-council"],
    sourceUrl: city,
    sourceLabel: "City of Ithaca",
  }),
  entity({
    id: "transit",
    kind: "issue",
    name: "Getting around Ithaca",
    subtitle: "Ithaca & campus · Transportation",
    summary: "Bus access, late-night trips, walking routes and everyday journeys between campus and town.",
    scope: "local",
    related: ["cornell-transit", "tcat", "ith-green-st-transit"],
    sourceUrl: tcat,
    sourceLabel: "TCAT",
  }),
  entity({
    id: "spaces",
    kind: "issue",
    name: "Our shared spaces",
    subtitle: "Ithaca · Public spaces",
    summary: "Public paths, green spaces, downtown and the places people gather.",
    scope: "local",
    related: ["ith-commons", "ith-stewart-park", "q-ith-commons-evenings"],
    sourceUrl: city,
    sourceLabel: "City of Ithaca",
  }),
  entity({
    id: "learning",
    kind: "issue",
    name: "Learning & libraries",
    subtitle: "Campus & town · Learning",
    summary: "Study spaces, library access and welcoming places to learn.",
    scope: "local",
    related: ["tcpl", "cu-olin-library", "q-cu-study-spaces"],
    sourceUrl: "https://www.tcpl.org/",
    sourceLabel: "Tompkins County Public Library",
  }),
  entity({
    id: "cu-student-voice",
    kind: "issue",
    name: "Student voice & governance",
    subtitle: "Cornell · Student government",
    summary: "How students are represented in university decisions and how student fees are allocated.",
    scope: "campus",
    related: ["cu-student-assembly", "cu-sa-meeting", "cu-activity-fee-brief"],
    sourceUrl: cornell,
    sourceLabel: "Cornell University",
  }),
  entity({
    id: "cu-campus-growth",
    kind: "issue",
    name: "Campus development",
    subtitle: "Cornell · Buildings & construction",
    summary: "New buildings, renovations and how construction changes routes and daily life.",
    scope: "campus",
    related: ["cu-college-ave-crossing", "cu-day-hall", "ith-collegetown"],
    sourceUrl: cornell,
    sourceLabel: "Cornell University",
  }),

  // Public offices and bodies. No officeholder is named without a checked source.
  entity({
    id: "ith-mayor",
    kind: "official",
    name: "Mayor of Ithaca",
    subtitle: "City of Ithaca · Elected office",
    summary: "An elected city office that works with the Common Council on local laws, the budget and city priorities.",
    scope: "local",
    topics: ["housing", "spaces"],
    related: ["ith-council", "ith-city-hall"],
    location: { lat: 42.439, lng: -76.4983, label: "City Hall, 108 E Green St", approximate: true },
    monogram: "M",
    office: { title: "Mayor", jurisdiction: "City of Ithaca", directoryUrl: city },
    sourceUrl: city,
    sourceLabel: "City of Ithaca",
  }),
  entity({
    id: "ith-council",
    kind: "official",
    name: "Ithaca Common Council",
    subtitle: "City of Ithaca · Legislative body",
    summary: "The city's elected legislative body. It adopts local laws and the city budget; its meetings are open to the public.",
    scope: "local",
    topics: ["housing", "transit", "spaces"],
    related: ["ith-council-meeting", "ith-mayor", "ith-city-hall"],
    location: { lat: 42.4391, lng: -76.4981, label: "City Hall council chambers", approximate: true },
    monogram: "CC",
    office: { title: "Common Council", jurisdiction: "City of Ithaca wards", directoryUrl: city },
    sourceUrl: city,
    sourceLabel: "City of Ithaca",
  }),
  entity({
    id: "tc-legislature",
    kind: "official",
    name: "Tompkins County Legislature",
    subtitle: "Tompkins County · Legislative body",
    summary: "The elected county body responsible for county laws, the county budget and services such as public health.",
    scope: "local",
    topics: ["transit", "housing"],
    related: ["tc-elections"],
    location: { lat: 42.4415, lng: -76.4961, label: "121 E Court St", approximate: true },
    monogram: "TC",
    office: { title: "County Legislature", jurisdiction: "Tompkins County", directoryUrl: county },
    sourceUrl: county,
    sourceLabel: "Tompkins County",
  }),
  entity({
    id: "ny-assembly-ithaca",
    kind: "official",
    name: "State Assembly member for Ithaca",
    subtitle: "New York State · Elected office",
    summary: "Represents the Ithaca area in the New York State Assembly, which votes on state laws and the state budget.",
    scope: "local",
    topics: ["housing"],
    related: ["tc-elections"],
    monogram: "NY",
    office: { title: "Member of Assembly", jurisdiction: "Assembly district including Ithaca", directoryUrl: "https://nyassembly.gov/mem/" },
    sourceUrl: "https://nyassembly.gov/mem/",
    sourceLabel: "New York State Assembly",
  }),
  entity({
    id: "cu-president",
    kind: "official",
    name: "Cornell University President",
    subtitle: "Cornell · University leadership",
    summary: "Cornell's chief executive, appointed by the Board of Trustees. Campus-wide policies and budgets run through this office.",
    scope: "campus",
    topics: ["cu-campus-growth", "cornell-climate"],
    related: ["cu-day-hall"],
    location: { lat: 42.4467, lng: -76.4829, label: "Day Hall", approximate: true },
    monogram: "P",
    office: { title: "University President", jurisdiction: "Cornell University", directoryUrl: cornell },
    sourceUrl: cornell,
    sourceLabel: "Cornell University",
  }),
  entity({
    id: "cu-student-assembly",
    kind: "official",
    name: "Cornell Student Assembly",
    subtitle: "Cornell · Student government",
    summary: "The elected undergraduate body that represents students to the administration and helps allocate the student activity fee.",
    scope: "campus",
    topics: ["cu-student-voice"],
    related: ["cu-sa-meeting", "cu-activity-fee-brief", "cu-willard-straight"],
    location: { lat: 42.4466, lng: -76.4858, label: "Willard Straight Hall area", approximate: true },
    monogram: "SA",
    office: { title: "Student Assembly", jurisdiction: "Cornell undergraduates", directoryUrl: cornell },
    sourceUrl: cornell,
    sourceLabel: "Cornell University",
  }),

  // Institutions, buildings and places.
  entity({
    id: "ith-city-hall",
    kind: "institution",
    name: "Ithaca City Hall",
    subtitle: "Government building · Downtown",
    summary: "Home to city offices and the Common Council chambers, where public meetings take place.",
    scope: "local",
    related: ["ith-council", "ith-mayor", "ith-council-meeting"],
    location: { lat: 42.4389, lng: -76.4986, label: "108 E Green St", approximate: true },
    sourceUrl: city,
    sourceLabel: "City of Ithaca",
  }),
  entity({
    id: "tc-elections",
    kind: "elections",
    name: "Tompkins County Board of Elections",
    subtitle: "Voter registration & polling-place lookup",
    summary: "Handles registration and absentee ballots for Tompkins County. Your polling place depends on your registered address — confirm it with the official lookup.",
    scope: "local",
    related: ["tc-legislature", "ny-assembly-ithaca"],
    location: { lat: 42.4405, lng: -76.4958, label: "Downtown Ithaca", approximate: true },
    sourceUrl: "https://voterlookup.elections.ny.gov/",
    sourceLabel: "NY voter lookup",
  }),
  entity({
    id: "tcpl",
    kind: "institution",
    name: "Tompkins County Public Library",
    subtitle: "Public library · Downtown",
    summary: "The county's public library, with study space, community rooms and public programs.",
    scope: "local",
    topics: ["learning"],
    related: ["q-cu-study-spaces"],
    location: { lat: 42.4382, lng: -76.4992, label: "101 E Green St", approximate: true },
    sourceUrl: "https://www.tcpl.org/",
    sourceLabel: "TCPL",
  }),
  entity({
    id: "cu-day-hall",
    kind: "building",
    name: "Day Hall",
    subtitle: "Cornell · Administration building",
    summary: "Cornell's main administration building, home to central university offices.",
    scope: "campus",
    related: ["cu-president"],
    location: { lat: 42.4467, lng: -76.4829, label: "Day Hall", approximate: true },
    sourceUrl: cornell,
    sourceLabel: "Cornell University",
  }),
  entity({
    id: "cu-willard-straight",
    kind: "building",
    name: "Willard Straight Hall",
    subtitle: "Cornell · Student union",
    summary: "The student union on Ho Plaza, with dining, meeting rooms and student organization space.",
    scope: "campus",
    related: ["cu-student-assembly"],
    location: { lat: 42.4464, lng: -76.4855, label: "Ho Plaza", approximate: true },
    sourceUrl: cornell,
    sourceLabel: "Cornell University",
  }),
  entity({
    id: "cu-olin-library",
    kind: "building",
    name: "Olin Library",
    subtitle: "Cornell · Library",
    summary: "A central research library on the Arts Quad, and one of the busiest study spaces on campus.",
    scope: "campus",
    topics: ["learning"],
    related: ["q-cu-study-spaces"],
    location: { lat: 42.4478, lng: -76.4843, label: "Arts Quad", approximate: true },
    sourceUrl: "https://www.library.cornell.edu/",
    sourceLabel: "Cornell University Library",
  }),
  entity({
    id: "cu-rpcc",
    kind: "building",
    name: "Robert Purcell Community Center",
    subtitle: "Cornell · North Campus hub",
    summary: "A North Campus hub with dining and residential services, and a common starting point for late trips across campus.",
    scope: "campus",
    topics: ["cornell-transit"],
    related: ["cu-north-campus", "q-cu-north-bus"],
    location: { lat: 42.4556, lng: -76.4778, label: "North Campus", approximate: true },
    sourceUrl: cornell,
    sourceLabel: "Cornell University",
  }),
  entity({
    id: "cu-north-campus",
    kind: "place",
    name: "North Campus",
    subtitle: "Cornell · Residential area",
    summary: "The residential area north of Fall Creek where most first-year students live.",
    scope: "campus",
    topics: ["cornell-transit"],
    related: ["cu-rpcc", "q-cu-north-bus", "cu-late-night-bus"],
    location: { lat: 42.4545, lng: -76.4762, label: "North of Fall Creek", approximate: true },
  }),
  entity({
    id: "ith-collegetown",
    kind: "place",
    name: "Collegetown",
    subtitle: "Ithaca · Neighborhood",
    summary: "A dense neighborhood just south of campus where many students rent.",
    scope: "local",
    topics: ["housing"],
    related: ["q-ith-collegetown-housing", "ith-collegetown-homes", "cu-college-ave-crossing"],
    location: { lat: 42.4418, lng: -76.4851, label: "College Ave & Dryden Rd", approximate: true },
  }),
  entity({
    id: "ith-commons",
    kind: "place",
    name: "Ithaca Commons",
    subtitle: "Ithaca · Downtown pedestrian mall",
    summary: "Downtown's pedestrian mall of shops and restaurants, and the site of many public festivals.",
    scope: "local",
    topics: ["spaces"],
    related: ["q-ith-commons-evenings", "ith-dia"],
    location: { lat: 42.4394, lng: -76.4968, label: "Downtown Ithaca", approximate: true },
  }),
  entity({
    id: "ith-stewart-park",
    kind: "place",
    name: "Stewart Park",
    subtitle: "Ithaca · City park",
    summary: "A lakeside city park at the southern tip of Cayuga Lake.",
    scope: "local",
    topics: ["spaces"],
    location: { lat: 42.4617, lng: -76.5049, label: "Cayuga Lake shore", approximate: true },
    sourceUrl: city,
    sourceLabel: "City of Ithaca",
  }),
  entity({
    id: "ith-green-st-transit",
    kind: "place",
    name: "Downtown TCAT stops",
    subtitle: "Ithaca · Transit transfer point",
    summary: "The downtown transfer area where many TCAT routes between campus and town meet.",
    scope: "local",
    topics: ["transit"],
    related: ["tcat"],
    location: { lat: 42.4386, lng: -76.4972, label: "Green St", approximate: true },
    sourceUrl: tcat,
    sourceLabel: "TCAT",
  }),

  // Organizations.
  entity({
    id: "tcat",
    kind: "organization",
    name: "TCAT",
    subtitle: "Tompkins Consolidated Area Transit",
    summary: "The public bus system serving Ithaca, Cornell and Tompkins County.",
    scope: "local",
    topics: ["cornell-transit", "transit"],
    related: ["ith-green-st-transit", "cu-late-night-bus"],
    sourceUrl: tcat,
    sourceLabel: "TCAT",
  }),
  entity({
    id: "ith-dia",
    kind: "organization",
    name: "Downtown Ithaca Alliance",
    subtitle: "Downtown organization",
    summary: "Organizes downtown programming, including the Apple Harvest Festival on the Commons.",
    scope: "local",
    topics: ["spaces"],
    related: ["ith-commons"],
    location: { lat: 42.4397, lng: -76.4962, label: "Ithaca Commons", approximate: true },
    sourceUrl: "https://www.downtownithaca.com/",
    sourceLabel: "Downtown Ithaca",
  }),
  entity({
    id: "ith-farmers-market",
    kind: "organization",
    name: "Ithaca Farmers Market",
    subtitle: "Market · Steamboat Landing",
    summary: "A long-running market of farm products, prepared food and crafts at Steamboat Landing.",
    scope: "local",
    location: { lat: 42.451, lng: -76.5093, label: "Steamboat Landing", approximate: true },
    sourceUrl: "https://ithacamarket.com/home/",
    sourceLabel: "Ithaca Farmers Market",
  }),
  entity({
    id: "cu-botanic-gardens",
    kind: "organization",
    name: "Cornell Botanic Gardens",
    subtitle: "Cornell · Gardens & natural areas",
    summary: "Gardens, an arboretum and natural areas on and around campus, with public tours.",
    scope: "campus",
    topics: ["cornell-climate"],
    location: { lat: 42.4497, lng: -76.4735, label: "Nevin Welcome Center", approximate: true },
    sourceUrl: "https://cornellbotanicgardens.org/",
    sourceLabel: "Cornell Botanic Gardens",
  }),

  // Public meetings described by type; dated occurrences live in the event listings.
  entity({
    id: "ith-council-meeting",
    kind: "meeting",
    name: "Common Council meetings",
    subtitle: "Public meeting · City Hall",
    summary: "Council meetings are open to the public and include time for public comment. Agendas are posted on the city calendar.",
    scope: "local",
    topics: ["housing", "transit"],
    related: ["ith-council", "ith-city-hall"],
    location: { lat: 42.4388, lng: -76.4984, label: "City Hall council chambers", approximate: true },
    meeting: { schedule: "Scheduled on the city calendar", bodyId: "ith-council", calendarUrl: "https://www.cityofithacany.gov/Calendar.aspx" },
    sourceUrl: "https://www.cityofithacany.gov/Calendar.aspx",
    sourceLabel: "City calendar",
  }),
  entity({
    id: "cu-sa-meeting",
    kind: "meeting",
    name: "Student Assembly meetings",
    subtitle: "Public meeting · Campus",
    summary: "Student Assembly meetings during the semester are generally open to students. Check the Assemblies' posted schedule for times and rooms.",
    scope: "campus",
    topics: ["cu-student-voice"],
    related: ["cu-student-assembly"],
    location: { lat: 42.4463, lng: -76.4852, label: "Central campus", approximate: true },
    meeting: { schedule: "During the semester; see the posted schedule", bodyId: "cu-student-assembly" },
    sourceUrl: cornell,
    sourceLabel: "Cornell University",
  }),

  // Samples: illustrative proposals and projects, not pending decisions.
  entity({
    id: "cu-late-night-bus",
    kind: "policy",
    name: "Late-night bus service to North Campus",
    subtitle: "Sample proposal · Transportation",
    summary: "An illustrative proposal to add later evening trips between central campus, Collegetown and North Campus, evaluated through a one-semester pilot.",
    details: ["Add later trips on weeknights during the semester.", "Publish ridership and cost data after the pilot.", "Compare against alternatives such as on-demand rides."],
    scope: "campus",
    topics: ["cornell-transit"],
    related: ["tcat", "cu-north-campus", "q-cu-north-bus", "cu-late-bus-brief"],
    location: { lat: 42.4528, lng: -76.4801, label: "North Campus to central campus", approximate: true },
    sample: true,
    policy: {
      status: "Illustrative proposal",
      category: "Transportation",
      institutionId: "tcat",
      steps: [
        { when: "Step 1", label: "Gather student input on late trips" },
        { when: "Step 2", label: "Estimate costs and driver availability" },
        { when: "Step 3", label: "Run and evaluate a one-semester pilot" },
      ],
      documents: [{ title: "TCAT routes and schedules", url: tcat }],
    },
  }),
  entity({
    id: "cu-parking-transit",
    kind: "policy",
    name: "Parking fees that fund campus transit",
    subtitle: "Sample proposal · Transportation",
    summary: "An illustrative idea: raise campus parking permit prices and direct the difference to bus service.",
    scope: "campus",
    topics: ["cornell-transit"],
    related: ["q-cu-parking-fees", "tcat"],
    sample: true,
    policy: {
      status: "Illustrative proposal",
      category: "Transportation",
      steps: [
        { when: "Step 1", label: "Publish current permit costs and transit spending" },
        { when: "Step 2", label: "Model effects on commuters with few alternatives" },
      ],
      documents: [{ title: "TCAT routes and schedules", url: tcat }],
    },
  }),
  entity({
    id: "ith-collegetown-homes",
    kind: "policy",
    name: "More homes near Collegetown transit",
    subtitle: "Sample proposal · Housing",
    summary: "An illustrative zoning change allowing taller apartment buildings on blocks close to frequent bus service.",
    scope: "local",
    topics: ["housing"],
    related: ["ith-collegetown", "q-ith-collegetown-housing", "ith-council"],
    location: { lat: 42.4412, lng: -76.4862, label: "Collegetown", approximate: true },
    sample: true,
    policy: {
      status: "Illustrative proposal",
      category: "Housing & zoning",
      institutionId: "ith-council",
      steps: [
        { when: "Step 1", label: "Planning board review" },
        { when: "Step 2", label: "Public hearing" },
        { when: "Step 3", label: "Council vote" },
      ],
      documents: [{ title: "City of Ithaca planning", url: city }],
    },
  }),
  entity({
    id: "cu-college-ave-crossing",
    kind: "project",
    name: "Safer crossing on College Avenue",
    subtitle: "Sample project · Streets",
    summary: "An illustrative street project marker: wider crosswalks and a raised crossing where students walk between Collegetown and campus.",
    scope: "campus",
    topics: ["cu-campus-growth", "transit"],
    related: ["ith-collegetown"],
    location: { lat: 42.4432, lng: -76.4853, label: "College Ave near campus", approximate: true },
    sample: true,
    policy: { status: "Illustrative project", category: "Streets", steps: [], documents: [] },
  }),

  // Sample briefs. Written by Polis as neutral context, not reporting.
  entity({
    id: "cu-late-bus-brief",
    kind: "news",
    name: "What a late-night North Campus bus pilot would involve",
    subtitle: "Sample brief · Transportation",
    summary: "Costs, driver schedules and ridership measures that shape any decision about later trips.",
    details: ["Late service competes with daytime frequency for the same drivers and buses.", "A pilot is easier to evaluate when success measures are agreed in advance."],
    scope: "campus",
    topics: ["cornell-transit"],
    related: ["cu-late-night-bus", "q-cu-north-bus"],
    sample: true,
    news: { source: "Polis sample brief", publishedAt: "2026-09-25T13:00:00.000Z" },
  }),
  entity({
    id: "ith-budget-brief",
    kind: "news",
    name: "How a city budget comes together",
    subtitle: "Sample explainer · Local government",
    summary: "Departments request funding, the council reviews it and residents can comment before a vote.",
    scope: "local",
    topics: ["housing", "spaces"],
    related: ["ith-council", "ith-council-meeting"],
    sample: true,
    news: { source: "Polis sample explainer", publishedAt: "2026-09-24T14:00:00.000Z" },
  }),
  entity({
    id: "cu-activity-fee-brief",
    kind: "news",
    name: "Where the student activity fee goes",
    subtitle: "Sample explainer · Student government",
    summary: "A short guide to how student organizations request funding and who decides.",
    scope: "campus",
    topics: ["cu-student-voice"],
    related: ["cu-student-assembly"],
    sample: true,
    news: { source: "Polis sample explainer", publishedAt: "2026-09-22T15:00:00.000Z" },
  }),
  entity({
    id: "ith-harvest-brief",
    kind: "news",
    name: "Apple Harvest weekend on the Commons",
    subtitle: "Sample brief · Community",
    summary: "The downtown festival fills the Commons this weekend. Check the organizer's page for hours and TCAT for service notices.",
    scope: "local",
    topics: ["spaces"],
    related: ["ith-commons", "ith-dia"],
    sample: true,
    news: { source: "Polis sample brief", publishedAt: "2026-09-26T12:00:00.000Z" },
  }),

  // Structured Commons questions. Perspectives summarize arguments people make;
  // they are not endorsements or claims about what any institution will do.
  entity({
    id: "q-cu-north-bus",
    kind: "question",
    name: "Should Cornell expand late-night bus service to North Campus?",
    subtitle: "Campus transportation",
    summary: "Late study sessions, labs and work shifts end after most buses slow down. Would later trips be worth the cost?",
    scope: "campus",
    topics: ["cornell-transit"],
    related: ["cu-late-night-bus", "tcat", "cu-north-campus", "cu-rpcc", "cu-late-bus-brief"],
    sample: true,
    debate: {
      context: "This is a Polis starter question based on a sample proposal. Share what you know from your own trips; the proposal itself is illustrative.",
      perspectives: [
        { label: "Reasons people support it", points: ["Safer trips home after late classes, labs and jobs.", "Fewer students relying on rides or walking alone."] },
        { label: "Concerns people raise", points: ["Cost per rider may be high on quiet nights.", "Drivers for late trips could come from daytime frequency."] },
        { label: "Questions to weigh", points: ["Who should pay: fees, the university or transit funding?", "What ridership would count as success?"] },
      ],
      documents: [{ title: "TCAT routes and schedules", url: tcat }],
      openedAt: "2026-09-21T14:00:00.000Z",
    },
  }),
  entity({
    id: "q-cu-parking-fees",
    kind: "question",
    name: "Should Cornell raise parking fees to fund campus transit?",
    subtitle: "Campus transportation",
    summary: "Parking and bus service compete for the same space and budget. Who should carry the cost?",
    scope: "campus",
    topics: ["cornell-transit"],
    related: ["cu-parking-transit", "tcat"],
    sample: true,
    debate: {
      context: "A Polis starter question about an illustrative idea. Consider people who drive because they have few alternatives.",
      perspectives: [
        { label: "Reasons people support it", points: ["Transit benefits more people per dollar than parking.", "Pricing can reduce congestion on campus roads."] },
        { label: "Concerns people raise", points: ["Staff with long commutes may have no practical bus option.", "Higher fees can fall hardest on lower-paid workers."] },
        { label: "Questions to weigh", points: ["Could fees scale by income or permit location?", "What bus improvements would the money buy?"] },
      ],
      documents: [{ title: "TCAT routes and schedules", url: tcat }],
      openedAt: "2026-09-19T14:00:00.000Z",
    },
  }),
  entity({
    id: "q-ith-collegetown-housing",
    kind: "question",
    name: "Should Ithaca allow denser housing near Cornell?",
    subtitle: "Local housing",
    summary: "More apartments near campus could ease rents, but change the look and feel of neighborhoods. What trade-offs matter to you?",
    scope: "local",
    topics: ["housing"],
    related: ["ith-collegetown", "ith-collegetown-homes", "ith-council", "ith-council-meeting"],
    sample: true,
    debate: {
      context: "A Polis starter question. The linked proposal is illustrative; real zoning changes go through city review and public hearings.",
      perspectives: [
        { label: "Reasons people support it", points: ["More supply near campus could ease competition for rentals.", "Students living closer can walk instead of drive."] },
        { label: "Concerns people raise", points: ["Taller buildings change neighborhood character and light.", "New units may not be affordable without requirements."] },
        { label: "Questions to weigh", points: ["Should new buildings include below-market units?", "How should infrastructure keep up?"] },
      ],
      documents: [{ title: "City of Ithaca", url: city }],
      openedAt: "2026-09-18T14:00:00.000Z",
    },
  }),
  entity({
    id: "q-cu-study-spaces",
    kind: "question",
    name: "Should more study spaces stay open around the clock?",
    subtitle: "Campus life",
    summary: "Late-night study space helps some students and costs staffing and security. Where should the line be?",
    scope: "campus",
    topics: ["learning"],
    related: ["cu-olin-library", "tcpl"],
    sample: true,
    debate: {
      context: "A Polis starter question. Share which spaces you use late and what would make them work better.",
      perspectives: [
        { label: "Reasons people support it", points: ["Schedules with jobs and labs push studying late.", "Shared spaces help students without quiet housing."] },
        { label: "Concerns people raise", points: ["Overnight staffing and security cost money.", "Round-the-clock access may encourage less sleep."] },
        { label: "Questions to weigh", points: ["Could a few buildings rotate late hours?", "Is safe transport home part of the answer?"] },
      ],
      documents: [{ title: "Cornell University Library", url: "https://www.library.cornell.edu/" }],
      openedAt: "2026-09-23T14:00:00.000Z",
    },
  }),
  entity({
    id: "q-ith-commons-evenings",
    kind: "question",
    name: "What would make downtown feel more welcoming in the evening?",
    subtitle: "Shared spaces",
    summary: "Lighting, events, places to sit and later hours all shape how the Commons feels after dark. What would bring you downtown?",
    scope: "local",
    topics: ["spaces"],
    related: ["ith-commons", "ith-dia"],
    sample: true,
    debate: {
      openEnded: true,
      context: "An open Polis starter question. There is no single right answer — describe what you would change and why.",
      perspectives: [
        { label: "Ideas people share", points: ["Regular free evening events and music.", "Better lighting and places to sit."] },
        { label: "Concerns people raise", points: ["Noise for nearby residents.", "Costs for small businesses staying open later."] },
      ],
      documents: [{ title: "Downtown Ithaca", url: "https://www.downtownithaca.com/" }],
      openedAt: "2026-09-24T14:00:00.000Z",
    },
  }),
];
