import type { CivicEntity } from "../types.ts";

// University of Florida / Gainesville civic context, using the same conventions
// as the Cornell catalog: offices without unverified names, approximate map
// positions, and samples labeled as samples.
const communityId = "uf";
const entity = (
  e: Omit<CivicEntity, "communityId" | "related" | "topics" | "sample"> &
    Partial<Pick<CivicEntity, "related" | "topics" | "sample">>,
): CivicEntity => ({ communityId, related: [], topics: [], sample: false, ...e });
const city = "https://www.gainesvillefl.gov/";
const county = "https://alachuacounty.us/";
const uf = "https://www.ufl.edu/";
const rts = "https://go-rts.com/";

export const ufEntities: CivicEntity[] = [
  entity({
    id: "uf-housing",
    kind: "issue",
    name: "Housing near campus",
    subtitle: "Gainesville · Housing",
    summary: "Rents, leases and how neighborhoods around UF grow.",
    scope: "local",
    related: ["gnv-midtown", "gnv-midtown-housing", "q-uf-midtown-housing", "gnv-commission"],
    sourceUrl: city,
    sourceLabel: "City of Gainesville",
  }),
  entity({
    id: "uf-street-safety",
    kind: "issue",
    name: "Safer streets",
    subtitle: "Gainesville · Walking & biking",
    summary: "Crossings, lighting and speeds on the busy streets that border campus.",
    scope: "local",
    related: ["uf-univ-ave-safety", "q-uf-university-ave", "gnv-midtown"],
    sourceUrl: city,
    sourceLabel: "City of Gainesville",
  }),
  entity({
    id: "uf-student-voice",
    kind: "issue",
    name: "Student voice & governance",
    subtitle: "UF · Student government",
    summary: "How students are represented in university decisions and how student fees are allocated.",
    scope: "campus",
    related: ["uf-student-government", "uf-senate-meeting", "uf-fee-brief", "q-uf-fees"],
    sourceUrl: uf,
    sourceLabel: "University of Florida",
  }),
  entity({
    id: "uf-campus-spaces",
    kind: "issue",
    name: "Campus spaces",
    subtitle: "UF · Libraries & outdoor space",
    summary: "Study spaces, shade and places to gather between classes.",
    scope: "campus",
    related: ["uf-library-west", "uf-marston", "uf-turlington", "q-uf-shade"],
    sourceUrl: uf,
    sourceLabel: "University of Florida",
  }),

  entity({
    id: "gnv-mayor",
    kind: "official",
    name: "Mayor of Gainesville",
    subtitle: "City of Gainesville · Elected office",
    summary: "An elected city office. The mayor serves on and presides over the Gainesville City Commission.",
    scope: "local",
    topics: ["uf-housing", "uf-street-safety"],
    related: ["gnv-commission", "gnv-city-hall"],
    location: { lat: 29.652, lng: -82.3232, label: "City Hall, 200 E University Ave", approximate: true },
    monogram: "M",
    office: { title: "Mayor", jurisdiction: "City of Gainesville", directoryUrl: city },
    sourceUrl: city,
    sourceLabel: "City of Gainesville",
  }),
  entity({
    id: "gnv-commission",
    kind: "official",
    name: "Gainesville City Commission",
    subtitle: "City of Gainesville · Governing body",
    summary: "The city's elected governing body. It adopts ordinances and the city budget in public meetings.",
    scope: "local",
    topics: ["uf-housing", "uf-transit", "uf-street-safety"],
    related: ["gnv-commission-meeting", "gnv-mayor", "gnv-city-hall"],
    location: { lat: 29.6518, lng: -82.3236, label: "City Hall auditorium", approximate: true },
    monogram: "CC",
    office: { title: "City Commission", jurisdiction: "City of Gainesville", directoryUrl: city },
    sourceUrl: city,
    sourceLabel: "City of Gainesville",
  }),
  entity({
    id: "alachua-commission",
    kind: "official",
    name: "Alachua County Commission",
    subtitle: "Alachua County · Governing body",
    summary: "The elected board that governs Alachua County, including the county budget and county-wide services.",
    scope: "local",
    topics: ["uf-transit"],
    related: ["alachua-elections"],
    location: { lat: 29.6511, lng: -82.3244, label: "County Administration Building", approximate: true },
    monogram: "AC",
    office: { title: "Board of County Commissioners", jurisdiction: "Alachua County", directoryUrl: county },
    sourceUrl: county,
    sourceLabel: "Alachua County",
  }),
  entity({
    id: "fl-house-gnv",
    kind: "official",
    name: "State House member for Gainesville",
    subtitle: "State of Florida · Elected office",
    summary: "Represents the Gainesville area in the Florida House of Representatives, which votes on state laws and the state budget.",
    scope: "local",
    related: ["alachua-elections"],
    monogram: "FL",
    office: { title: "State Representative", jurisdiction: "House district including Gainesville", directoryUrl: "https://www.myfloridahouse.gov/" },
    sourceUrl: "https://www.myfloridahouse.gov/",
    sourceLabel: "Florida House",
  }),
  entity({
    id: "uf-president",
    kind: "official",
    name: "University of Florida President",
    subtitle: "UF · University leadership",
    summary: "UF's chief executive, selected by the university's Board of Trustees. Campus-wide policies and budgets run through this office.",
    scope: "campus",
    topics: ["uf-campus-spaces", "uf-climate"],
    related: ["uf-tigert-hall"],
    location: { lat: 29.649, lng: -82.3417, label: "Tigert Hall", approximate: true },
    monogram: "P",
    office: { title: "University President", jurisdiction: "University of Florida", directoryUrl: uf },
    sourceUrl: uf,
    sourceLabel: "University of Florida",
  }),
  entity({
    id: "uf-student-government",
    kind: "official",
    name: "UF Student Government",
    subtitle: "UF · Student government",
    summary: "Student-elected executive, legislative and judicial branches. The Student Senate votes on the Activity & Service fee budget.",
    scope: "campus",
    topics: ["uf-student-voice"],
    related: ["uf-senate-meeting", "uf-fee-brief", "uf-reitz-union"],
    location: { lat: 29.6464, lng: -82.3476, label: "Reitz Union", approximate: true },
    monogram: "SG",
    office: { title: "Student Government", jurisdiction: "UF students", directoryUrl: uf },
    sourceUrl: uf,
    sourceLabel: "University of Florida",
  }),

  entity({
    id: "gnv-city-hall",
    kind: "institution",
    name: "Gainesville City Hall",
    subtitle: "Government building · Downtown",
    summary: "Home to city offices and the auditorium where the City Commission meets.",
    scope: "local",
    related: ["gnv-commission", "gnv-mayor", "gnv-commission-meeting"],
    location: { lat: 29.6519, lng: -82.3234, label: "200 E University Ave", approximate: true },
    sourceUrl: city,
    sourceLabel: "City of Gainesville",
  }),
  entity({
    id: "alachua-elections",
    kind: "elections",
    name: "Alachua County Supervisor of Elections",
    subtitle: "Voter registration & polling-place lookup",
    summary: "Handles registration and vote-by-mail requests for Alachua County. Your polling place depends on your registered address — confirm it with the official lookup.",
    scope: "local",
    related: ["alachua-commission", "fl-house-gnv"],
    location: { lat: 29.6572, lng: -82.3252, label: "North Main St", approximate: true },
    sourceUrl: "https://registration.elections.myflorida.com/CheckVoterStatus",
    sourceLabel: "Florida voter lookup",
  }),
  entity({
    id: "uf-tigert-hall",
    kind: "building",
    name: "Tigert Hall",
    subtitle: "UF · Administration building",
    summary: "UF's main administration building, home to central university offices.",
    scope: "campus",
    related: ["uf-president"],
    location: { lat: 29.649, lng: -82.3417, label: "Tigert Hall", approximate: true },
    sourceUrl: uf,
    sourceLabel: "University of Florida",
  }),
  entity({
    id: "uf-reitz-union",
    kind: "building",
    name: "Reitz Union",
    subtitle: "UF · Student union",
    summary: "The student union, with meeting rooms, dining and student organization offices, and a busy stop for campus buses.",
    scope: "campus",
    topics: ["uf-transit"],
    related: ["uf-student-government", "uf-senate-meeting"],
    location: { lat: 29.6463, lng: -82.3479, label: "Museum Rd", approximate: true },
    sourceUrl: uf,
    sourceLabel: "University of Florida",
  }),
  entity({
    id: "uf-library-west",
    kind: "building",
    name: "Library West",
    subtitle: "UF · Library",
    summary: "A humanities and social sciences library near University Avenue and one of the busiest study spaces on campus.",
    scope: "campus",
    topics: ["uf-campus-spaces"],
    related: ["q-uf-shade"],
    location: { lat: 29.6513, lng: -82.3429, label: "Near University Ave", approximate: true },
    sourceUrl: "https://uflib.ufl.edu/",
    sourceLabel: "UF Libraries",
  }),
  entity({
    id: "uf-marston",
    kind: "building",
    name: "Marston Science Library",
    subtitle: "UF · Library",
    summary: "The science and engineering library, a popular group-study space.",
    scope: "campus",
    topics: ["uf-campus-spaces"],
    location: { lat: 29.6481, lng: -82.3439, label: "Central campus", approximate: true },
    sourceUrl: "https://uflib.ufl.edu/",
    sourceLabel: "UF Libraries",
  }),
  entity({
    id: "uf-stadium",
    kind: "building",
    name: "Ben Hill Griffin Stadium",
    subtitle: "UF · Stadium",
    summary: "The football stadium. Game days change traffic, parking and bus service around campus.",
    scope: "campus",
    topics: ["uf-transit"],
    location: { lat: 29.6499, lng: -82.3486, label: "Stadium Rd", approximate: true },
    sourceUrl: uf,
    sourceLabel: "University of Florida",
  }),
  entity({
    id: "uf-turlington",
    kind: "place",
    name: "Turlington Plaza",
    subtitle: "UF · Campus plaza",
    summary: "A central plaza where student organizations table and people pass between classes.",
    scope: "campus",
    topics: ["uf-campus-spaces"],
    related: ["q-uf-shade", "uf-shade-study"],
    location: { lat: 29.6489, lng: -82.3444, label: "Central campus", approximate: true },
  }),
  entity({
    id: "uf-plaza-americas",
    kind: "place",
    name: "Plaza of the Americas",
    subtitle: "UF · Campus green",
    summary: "An open green framed by historic buildings and a common place to meet or study outside.",
    scope: "campus",
    topics: ["uf-campus-spaces"],
    location: { lat: 29.6498, lng: -82.3426, label: "Central campus", approximate: true },
  }),
  entity({
    id: "uf-lake-alice",
    kind: "place",
    name: "Lake Alice",
    subtitle: "UF · Natural area",
    summary: "A lake and conservation area on the west side of campus.",
    scope: "campus",
    topics: ["uf-climate"],
    location: { lat: 29.6431, lng: -82.3612, label: "West campus", approximate: true },
  }),
  entity({
    id: "gnv-midtown",
    kind: "place",
    name: "Midtown",
    subtitle: "Gainesville · Neighborhood",
    summary: "The busy strip of restaurants and apartments along University Avenue across from campus.",
    scope: "local",
    topics: ["uf-housing", "uf-street-safety"],
    related: ["q-uf-midtown-housing", "gnv-midtown-housing", "uf-univ-ave-safety"],
    location: { lat: 29.6524, lng: -82.3437, label: "W University Ave", approximate: true },
  }),
  entity({
    id: "gnv-bo-diddley",
    kind: "place",
    name: "Bo Diddley Plaza",
    subtitle: "Gainesville · Downtown plaza",
    summary: "A downtown plaza that hosts concerts, markets and community gatherings.",
    scope: "local",
    related: ["gnv-union-market"],
    location: { lat: 29.6513, lng: -82.3247, label: "Downtown Gainesville", approximate: true },
    sourceUrl: city,
    sourceLabel: "City of Gainesville",
  }),
  entity({
    id: "gnv-depot-park",
    kind: "place",
    name: "Depot Park",
    subtitle: "Gainesville · City park",
    summary: "A large park south of downtown with trails, a playground and event space.",
    scope: "local",
    location: { lat: 29.6437, lng: -82.319, label: "South of downtown", approximate: true },
    sourceUrl: city,
    sourceLabel: "City of Gainesville",
  }),

  entity({
    id: "rts",
    kind: "organization",
    name: "Gainesville RTS",
    subtitle: "Regional Transit System",
    summary: "The city bus system serving Gainesville and the UF campus, including late-night routes. Check RTS for current fare rules.",
    scope: "local",
    topics: ["uf-transit"],
    related: ["uf-later-gator", "uf-reitz-union"],
    sourceUrl: rts,
    sourceLabel: "Gainesville RTS",
  }),
  entity({
    id: "gnv-union-market",
    kind: "organization",
    name: "Union Street Farmers Market",
    subtitle: "Market · Bo Diddley Plaza",
    summary: "A weekly downtown market of local produce, food and crafts. Confirm hours with the organizer.",
    scope: "local",
    related: ["gnv-bo-diddley"],
    location: { lat: 29.6515, lng: -82.3244, label: "Bo Diddley Plaza", approximate: true },
  }),

  entity({
    id: "gnv-commission-meeting",
    kind: "meeting",
    name: "City Commission meetings",
    subtitle: "Public meeting · City Hall",
    summary: "Commission meetings are open to the public and include time for public comment. Agendas are posted on the city's meeting calendar.",
    scope: "local",
    topics: ["uf-housing", "uf-street-safety"],
    related: ["gnv-commission", "gnv-city-hall"],
    location: { lat: 29.6521, lng: -82.3236, label: "City Hall auditorium", approximate: true },
    meeting: { schedule: "Scheduled on the city meeting calendar", bodyId: "gnv-commission", calendarUrl: city },
    sourceUrl: city,
    sourceLabel: "City of Gainesville",
  }),
  entity({
    id: "uf-senate-meeting",
    kind: "meeting",
    name: "Student Senate meetings",
    subtitle: "Public meeting · Reitz Union",
    summary: "Student Senate meetings during the semester are open to students. Check Student Government's posted schedule for times.",
    scope: "campus",
    topics: ["uf-student-voice"],
    related: ["uf-student-government"],
    location: { lat: 29.6461, lng: -82.3481, label: "Reitz Union", approximate: true },
    meeting: { schedule: "During the semester; see the posted schedule", bodyId: "uf-student-government" },
    sourceUrl: uf,
    sourceLabel: "University of Florida",
  }),

  entity({
    id: "uf-later-gator",
    kind: "policy",
    name: "Longer late-night bus service",
    subtitle: "Sample proposal · Transportation",
    summary: "An illustrative proposal to run late-night routes between campus, Midtown and downtown more often on weekends.",
    details: ["Increase late-night frequency on weekend nights.", "Publish ridership and cost data each semester.", "Coordinate with game-day and event schedules."],
    scope: "local",
    topics: ["uf-transit"],
    related: ["rts", "q-uf-late-service", "uf-late-bus-brief"],
    location: { lat: 29.6516, lng: -82.3395, label: "Campus to downtown corridor", approximate: true },
    sample: true,
    policy: {
      status: "Illustrative proposal",
      category: "Transportation",
      institutionId: "rts",
      steps: [
        { when: "Step 1", label: "Collect rider input" },
        { when: "Step 2", label: "Estimate costs and driver availability" },
        { when: "Step 3", label: "Pilot for one semester" },
      ],
      documents: [{ title: "RTS routes and schedules", url: rts }],
    },
  }),
  entity({
    id: "uf-univ-ave-safety",
    kind: "project",
    name: "University Avenue crossing improvements",
    subtitle: "Sample project · Streets",
    summary: "An illustrative street project marker: longer crossing times, better lighting and slower speeds where students cross University Avenue.",
    scope: "local",
    topics: ["uf-street-safety"],
    related: ["gnv-midtown", "q-uf-university-ave"],
    location: { lat: 29.6519, lng: -82.3415, label: "W University Ave", approximate: true },
    sample: true,
    policy: {
      status: "Illustrative project",
      category: "Streets",
      steps: [
        { when: "Step 1", label: "Review crash and crossing data" },
        { when: "Step 2", label: "Public workshop" },
      ],
      documents: [{ title: "City of Gainesville", url: city }],
    },
  }),
  entity({
    id: "gnv-midtown-housing",
    kind: "policy",
    name: "Taller student housing near Midtown",
    subtitle: "Sample proposal · Housing",
    summary: "An illustrative zoning change allowing taller apartment buildings on blocks across from campus.",
    scope: "local",
    topics: ["uf-housing"],
    related: ["gnv-midtown", "q-uf-midtown-housing", "gnv-commission"],
    location: { lat: 29.6531, lng: -82.3448, label: "Midtown", approximate: true },
    sample: true,
    policy: {
      status: "Illustrative proposal",
      category: "Housing & zoning",
      institutionId: "gnv-commission",
      steps: [
        { when: "Step 1", label: "Plan board review" },
        { when: "Step 2", label: "Public hearing" },
        { when: "Step 3", label: "Commission vote" },
      ],
      documents: [{ title: "City of Gainesville", url: city }],
    },
  }),
  entity({
    id: "uf-shade-study",
    kind: "policy",
    name: "More shaded outdoor study space",
    subtitle: "Sample proposal · Campus spaces",
    summary: "An illustrative idea: add shade structures, seating and outlets on central plazas.",
    scope: "campus",
    topics: ["uf-campus-spaces", "uf-climate"],
    related: ["uf-turlington", "q-uf-shade"],
    location: { lat: 29.6486, lng: -82.3447, label: "Turlington Plaza", approximate: true },
    sample: true,
    policy: { status: "Illustrative proposal", category: "Campus spaces", steps: [], documents: [] },
  }),

  entity({
    id: "uf-late-bus-brief",
    kind: "news",
    name: "What late-night bus options look like for students",
    subtitle: "Sample brief · Transportation",
    summary: "How late routes are planned, what they cost and how ridership is measured.",
    scope: "local",
    topics: ["uf-transit"],
    related: ["uf-later-gator", "rts"],
    sample: true,
    news: { source: "Polis sample brief", publishedAt: "2026-09-25T13:00:00.000Z" },
  }),
  entity({
    id: "gnv-budget-brief",
    kind: "news",
    name: "How the city budget comes together",
    subtitle: "Sample explainer · Local government",
    summary: "Departments request funding, the commission reviews it and residents can speak before a vote.",
    scope: "local",
    topics: ["uf-housing"],
    related: ["gnv-commission", "gnv-commission-meeting"],
    sample: true,
    news: { source: "Polis sample explainer", publishedAt: "2026-09-24T14:00:00.000Z" },
  }),
  entity({
    id: "uf-fee-brief",
    kind: "news",
    name: "Where the Activity & Service fee goes",
    subtitle: "Sample explainer · Student government",
    summary: "A short guide to how student organizations request funding and how the Senate decides.",
    scope: "campus",
    topics: ["uf-student-voice"],
    related: ["uf-student-government", "q-uf-fees"],
    sample: true,
    news: { source: "Polis sample explainer", publishedAt: "2026-09-22T15:00:00.000Z" },
  }),
  entity({
    id: "uf-gameday-brief",
    kind: "news",
    name: "Game-day weekends: what changes around campus",
    subtitle: "Sample brief · Community",
    summary: "Road closures, parking and bus detours shift on home-game days. Check official notices before you travel.",
    scope: "campus",
    topics: ["uf-transit"],
    related: ["uf-stadium", "rts"],
    sample: true,
    news: { source: "Polis sample brief", publishedAt: "2026-09-26T12:00:00.000Z" },
  }),

  entity({
    id: "q-uf-late-service",
    kind: "question",
    name: "Should late-night buses run more often on weekends?",
    subtitle: "Local transportation",
    summary: "Weekend nights move a lot of students between campus, Midtown and downtown. Is more late service the right use of transit money?",
    scope: "local",
    topics: ["uf-transit"],
    related: ["uf-later-gator", "rts", "gnv-midtown", "uf-late-bus-brief"],
    sample: true,
    debate: {
      context: "A Polis starter question based on a sample proposal. Share what your late trips are actually like.",
      perspectives: [
        { label: "Reasons people support it", points: ["Safer ways home than walking or driving late.", "Less demand for parking downtown and in Midtown."] },
        { label: "Concerns people raise", points: ["Late service is costly to staff.", "Money could instead improve daytime frequency."] },
        { label: "Questions to weigh", points: ["Which nights and routes matter most?", "How should success be measured?"] },
      ],
      documents: [{ title: "RTS routes and schedules", url: rts }],
      openedAt: "2026-09-21T14:00:00.000Z",
    },
  }),
  entity({
    id: "q-uf-university-ave",
    kind: "question",
    name: "How should University Avenue be redesigned for people walking?",
    subtitle: "Street safety",
    summary: "Thousands of students cross University Avenue every day. What would make crossing it safer without gridlock?",
    scope: "local",
    topics: ["uf-street-safety"],
    related: ["uf-univ-ave-safety", "gnv-midtown", "gnv-commission"],
    sample: true,
    debate: {
      openEnded: true,
      context: "An open Polis starter question. Describe the crossings you use and what would change your trip.",
      perspectives: [
        { label: "Ideas people share", points: ["Longer walk signals and raised crosswalks.", "Lower speed limits and better lighting."] },
        { label: "Concerns people raise", points: ["Slower traffic on a major corridor.", "Construction disruption for nearby businesses."] },
      ],
      documents: [{ title: "City of Gainesville", url: city }],
      openedAt: "2026-09-20T14:00:00.000Z",
    },
  }),
  entity({
    id: "q-uf-midtown-housing",
    kind: "question",
    name: "Should Gainesville allow taller student housing near campus?",
    subtitle: "Local housing",
    summary: "Taller buildings could add beds near campus but change surrounding neighborhoods. What should guide those decisions?",
    scope: "local",
    topics: ["uf-housing"],
    related: ["gnv-midtown-housing", "gnv-midtown", "gnv-commission", "gnv-commission-meeting"],
    sample: true,
    debate: {
      context: "A Polis starter question. The linked proposal is illustrative; zoning changes go through city review and public hearings.",
      perspectives: [
        { label: "Reasons people support it", points: ["More beds near campus could ease rent pressure.", "Walkable housing reduces car trips."] },
        { label: "Concerns people raise", points: ["Neighborhood character and traffic.", "Luxury units may not help students on tight budgets."] },
        { label: "Questions to weigh", points: ["Should new buildings include lower-cost units?", "Can infrastructure keep up?"] },
      ],
      documents: [{ title: "City of Gainesville", url: city }],
      openedAt: "2026-09-18T14:00:00.000Z",
    },
  }),
  entity({
    id: "q-uf-shade",
    kind: "question",
    name: "Should UF add more shaded outdoor study space?",
    subtitle: "Campus spaces",
    summary: "Florida heat makes central plazas hard to use for much of the year. Is shade a priority for campus spending?",
    scope: "campus",
    topics: ["uf-campus-spaces", "uf-climate"],
    related: ["uf-shade-study", "uf-turlington", "uf-library-west"],
    sample: true,
    debate: {
      context: "A Polis starter question about an illustrative idea. Share where you study between classes.",
      perspectives: [
        { label: "Reasons people support it", points: ["More usable space without new buildings.", "Relief from heat on the walk between classes."] },
        { label: "Concerns people raise", points: ["Maintenance and hurricane-season durability.", "Other campus spaces may be a higher priority."] },
      ],
      documents: [{ title: "University of Florida", url: uf }],
      openedAt: "2026-09-23T14:00:00.000Z",
    },
  }),
  entity({
    id: "q-uf-fees",
    kind: "question",
    name: "Should student fees fund more late-night programming?",
    subtitle: "Student government",
    summary: "Student fees support organizations and events. Would late-night alternatives be worth a larger share?",
    scope: "campus",
    topics: ["uf-student-voice"],
    related: ["uf-student-government", "uf-fee-brief", "uf-senate-meeting"],
    sample: true,
    debate: {
      context: "A Polis starter question. Fee decisions belong to Student Government; this is a place to share perspectives first.",
      perspectives: [
        { label: "Reasons people support it", points: ["Safe social options close to campus.", "Programming reaches students who skip daytime events."] },
        { label: "Concerns people raise", points: ["Less funding for existing organizations.", "Attendance at late events can be unpredictable."] },
      ],
      documents: [{ title: "University of Florida", url: uf }],
      openedAt: "2026-09-19T14:00:00.000Z",
    },
  }),
];
