"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowLeft,ArrowRight,Check,Bookmark,BookmarkCheck,CalendarDays,MapPin,Clock,Info,Lock,Users,Globe,ChevronRight} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Slider} from "@/components/ui/slider";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Button} from "@/components/ui/button";
import {items,itemById,kinds,friends,questions,singular,type CivicItem,type Kind,type Audience} from "@/lib/polis-data";
import {type DemoState,type Ranking} from "@/lib/polis-state";
import {ItemIcon,Avatar,AvatarStack,Score} from "./common";

export function RankDialog({initialItem,state,onClose,onSave,onCompare,persisted=false}:{initialItem?:CivicItem;state:DemoState;onClose:()=>void;onSave:(r:Ranking)=>void|Promise<void>;onCompare:(a:string,b:string)=>void|Promise<void>;persisted?:boolean}){
  const [item,setItem]=useState(initialItem);
  const old=state.rankings.find(r=>r.itemId===initialItem?.id);
  const [score,setScore]=useState<number|null>(old?.score??null);
  const [note,setNote]=useState(old?.note??"");
  const [audience,setAudience]=useState<Audience>(old?.audience??"Private");
  const [kind,setKind]=useState<Kind>("Policies");
  const [comparison,setComparison]=useState<CivicItem|null>(null);
  function choose(next:CivicItem){const saved=state.rankings.find(r=>r.itemId===next.id);setItem(next);setScore(saved?.score??null);setNote(saved?.note??"");setAudience(saved?.audience??"Private");}
  const [saving,setSaving]=useState(false),[saveError,setSaveError]=useState("");
  async function save(){if(!item||score===null)return;const other=state.rankings.find(r=>r.itemId!==item.id&&itemById[r.itemId].kind===item.kind);const existed=state.rankings.some(r=>r.itemId===item.id);setSaving(true);try{await onSave({itemId:item.id,score,note:note.trim(),audience:persisted?"Private":audience});if(other&&!existed)setComparison(itemById[other.itemId]);else onClose();}catch(e){setSaveError(e instanceof Error?e.message:"Unable to save. Please retry.");}finally{setSaving(false);}}
  const question=item?questions[item.kind]:null;
  return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="polis-dialog rank-dialog"><DialogHeader><DialogTitle>{comparison?"One quick comparison":item?"Add your perspective":"What would you like to rank?"}</DialogTitle><DialogDescription>{comparison?"Which comes first in your personal list? Your support scores stay separate.":item?"Your view can evolve. You can change this anytime.":"Explore a sample, form a view, and make the list your own."}</DialogDescription></DialogHeader>
    {comparison&&item?<div className="comparison-flow">{saveError&&<p className="form-error" role="alert">{saveError}</p>}<div className="saved-confirmation"><Check size={16}/>Your rating is saved.</div>{[item,comparison].map(option=><button key={option.id} className="comparison-choice" onClick={async()=>{try{await onCompare(option.id,option.id===item.id?comparison.id:item.id);onClose();}catch(e){setSaveError(e instanceof Error?e.message:"Please retry.");}}}><ItemIcon item={option}/><span><span className="eyeline">{option.topic}</span><strong>{option.title}</strong></span><ArrowRight size={20}/></button>)}<Button variant="ghost" className="btn plain full" onClick={onClose}>Keep the current order</Button></div>:!item?<Tabs value={kind} onValueChange={value=>setKind(value as Kind)}><TabsList className="picker-tabs">{kinds.map(k=><TabsTrigger key={k} value={k}>{k}</TabsTrigger>)}</TabsList>{kinds.map(k=><TabsContent key={k} value={k}><div className="rank-picker">{items.filter(i=>i.kind===k).map(i=><button key={i.id} onClick={()=>choose(i)} className="picker-row"><ItemIcon item={i}/><span><strong>{i.title}</strong><span>{i.topic}</span></span><ChevronRight size={18}/></button>)}</div></TabsContent>)}</Tabs>:<div className="rating-flow">
      {!initialItem&&<button className="text-button" onClick={()=>setItem(undefined)}><ArrowLeft size={15}/>Choose another item</button>}
      <div className="rating-subject"><ItemIcon item={item}/><div><span className="eyeline">Sample {singular[item.kind]}</span><h3>{item.title}</h3></div></div>
      <fieldset className="rating-field"><legend>{question?.title}</legend><div className="chosen-score">{score===null?<span className="unrated-score">Your call.</span>:<><strong>{score.toFixed(1)}</strong><span>/ 10</span></>}</div><Slider value={[score??5]} onValueChange={value=>setScore(value[0])} min={0} max={10} step={0.1} aria-label={question?.title}/><div className="slider-labels"><span>{question?.low}</span><span>{question?.high}</span></div><div className="rating-shortcuts"><button onClick={()=>setScore(2)}>{item.kind==="News"?"Not very useful":item.kind==="Events"?"Not for me":"Oppose"}</button><button onClick={()=>setScore(5)}>{item.kind==="News"||item.kind==="Events"?"Somewhat":"Mixed"}</button><button onClick={()=>setScore(8)}>{item.kind==="News"?"Useful":item.kind==="Events"?"Recommend":"Support"}</button></div></fieldset>
      <label className="field-label" htmlFor="ranking-note">Add a note <span>optional</span></label><textarea id="ranking-note" value={note} onChange={e=>setNote(e.target.value)} maxLength={280} placeholder="What shaped your perspective?" rows={3}/>
      {persisted?<p className="small-notice"><Lock size={14}/>Only you can see this ranking and note. Publish a selected list separately to share.</p>:<div className="visibility-row"><div><label className="field-label" htmlFor="rank-audience">Audience preview</label><p>Saved on this device. Nothing is published.</p></div><Select value={audience} onValueChange={value=>setAudience(value as Audience)}><SelectTrigger id="rank-audience" className="audience-select"><SelectValue/></SelectTrigger><SelectContent>{(["Private","Friends","Public"] as Audience[]).map(a=><SelectItem key={a} value={a}>{a==="Private"?<Lock size={14}/>:a==="Friends"?<Users size={14}/>:<Globe size={14}/>}{a}</SelectItem>)}</SelectContent></Select></div>}
      {item.kind==="News"&&<p className="small-notice"><Info size={14}/>This rates usefulness, not factual accuracy.</p>}{item.kind==="Events"&&<p className="small-notice"><Info size={14}/>Try rating the sample experience. This does not record real attendance.</p>}
      {saveError&&<p className="form-error" role="alert">{saveError}</p>}<Button className="btn primary full" disabled={score===null||saving} onClick={save}>Save ranking<Check size={17}/></Button><Button variant="ghost" className="btn plain full" onClick={onClose}>I don’t know enough yet</Button>
    </div>}
  </DialogContent></Dialog>;
}

export function DetailSheet({item,state,onClose,onOpen,onRank,onSave,onPlan}:{item:CivicItem|null;state:DemoState;onClose:()=>void;onOpen:(i:CivicItem)=>void;onRank:(i:CivicItem)=>void;onSave:(id:string)=>void;onPlan:(id:string)=>void}){
  const [scoreScope,setScoreScope]=useState("Community");
  const detailBody=useRef<HTMLDivElement>(null);
  useEffect(()=>{detailBody.current?.scrollTo({top:0});},[item?.id]);
  if(!item)return null;
  const own=state.rankings.find(r=>r.itemId===item.id);
  const friendRatings=friends.filter(f=>state.following.includes(f.id)).map(f=>(f.ratings as Record<string,number|undefined>)[item.id]).filter((r):r is number=>typeof r==="number");
  const displayed=scoreScope==="You"?own?.score:scoreScope==="Friends"?(friendRatings.length?friendRatings.reduce((a,b)=>a+b,0)/friendRatings.length:undefined):item.score;
  return <Sheet open onOpenChange={open=>{if(!open)onClose();}}><SheetContent className="detail-sheet"><SheetHeader><div className="detail-kind">{item.topic} · {item.kind==="Politicians"?"Fictional candidate":"Sample "+singular[item.kind]}</div><SheetTitle>{item.title}</SheetTitle><SheetDescription>{item.subtitle}</SheetDescription></SheetHeader><div className="detail-body" ref={detailBody}>
    {item.id==="homes"||item.kind==="News"?<img className="detail-image" src="/images/community-street.webp" alt="Illustrative college-town street" width={1536} height={1024}/>:item.initials?<div className="candidate-identity"><Avatar initials={item.initials} color={item.color} size="hero"/><span>Sample candidate<br/><strong>No real office or affiliation</strong></span></div>:null}
    {item.event&&<div className="event-facts"><span><CalendarDays size={18}/>{item.event.weekday}, September {item.event.day}, 2026</span><span><Clock size={18}/>{item.event.time}</span><span><MapPin size={18}/>{item.event.place}</span><span><AvatarStack ids={item.event.friends}/>{item.event.friends.length} sample friends planning to go</span></div>}
    <p className="detail-summary">{item.summary}</p>
    <section className="detail-section"><h3>{item.kind==="News"?"The short read":item.kind==="Politicians"?"Sample positions":item.kind==="Events"?"What to expect":"Inside the proposal"}</h3><ul>{item.details.map(text=><li key={text}>{text}</li>)}</ul></section>
    <section className="detail-section consideration"><h3>{item.kind==="Events"?"About this event":"Questions worth asking"}</h3>{item.considerations.map(text=><p key={text}>{text}</p>)}</section>
    <section className="detail-scores"><div className="section-heading"><h3>{item.kind==="News"?"How useful is it?":item.kind==="Events"?"Sample experience ratings":"Where perspectives stand"}</h3><Select value={scoreScope} onValueChange={setScoreScope}><SelectTrigger aria-label="Rating audience"><SelectValue/></SelectTrigger><SelectContent>{["Community","Friends","You"].map(s=><SelectItem value={s} key={s}>{s}</SelectItem>)}</SelectContent></Select></div><div className="score-explanation">{displayed!==undefined?<Score value={displayed}/>:<span className="no-score">No rating yet</span>}<p>{scoreScope==="Community"?item.count+" illustrative ratings. These are demo opinions, not representative polling.":scoreScope==="Friends"?friendRatings.length+" ratings from sample friends you follow.":own?"Your personal view. Only saved on this device.":"Start with your own perspective."}</p></div>{item.kind==="News"&&<p className="metadata">Usefulness ratings do not verify accuracy.</p>}</section>
    <section className="detail-section related-section"><h3>{item.kind==="Events"?"Get the context":"Keep exploring"}</h3>{item.related.map(id=><button key={id} onClick={()=>onOpen(itemById[id])} className="related-row"><ItemIcon item={itemById[id]}/><span><span className="metadata">{itemById[id].kind}</span><strong>{itemById[id].title}</strong></span><ChevronRight size={17}/></button>)}</section>
    <p className="source-note"><Info size={15}/>{item.source?item.source+" · Original fictional demonstration content.":"Illustrative demo content. No real policy, candidate, event, or public record is represented."}</p>
  </div><div className="detail-actions">{item.event?<><Button className={"btn "+(state.plans.includes(item.id)?"secondary":"primary")} onClick={()=>onPlan(item.id)}>{state.plans.includes(item.id)?<Check size={17}/>:<CalendarDays size={17}/>}{state.plans.includes(item.id)?"In your plans":"Add to my plans"}</Button><Button className="btn secondary" variant="outline" onClick={()=>onRank(item)}>Rate sample</Button></>:<Button className="btn primary" onClick={()=>onRank(item)}>{own?"Edit your ranking":"Rank this "+singular[item.kind]}<ArrowRight size={17}/></Button>}<button className="icon-btn" onClick={()=>onSave(item.id)} aria-label={(state.saved.includes(item.id)?"Unsave ":"Save ")+item.title}>{state.saved.includes(item.id)?<BookmarkCheck size={21}/>:<Bookmark size={21}/>}</button></div></SheetContent></Sheet>;
}

export function AboutDialog({onClose}:{onClose:()=>void}){return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="polis-dialog"><DialogHeader><DialogTitle>Welcome to your demo community.</DialogTitle><DialogDescription>A working first look at Polis, set in Ithaca.</DialogDescription></DialogHeader><div className="about-copy"><p>Try ranking a policy, reading a story, exploring the map, and making a plan with sample friends.</p><p>People, policies, candidates, news, ratings, and events are fictional. The map and street photograph are illustrative. No real political views are assumed for you.</p><p>Your rankings, bookmarks, and plans are saved in this browser. Audience settings preview how sharing would work; nothing is published or sent. Friend markers show sample event RSVPs, never live location.</p><Button className="btn primary full" onClick={onClose}>Explore Polis<ArrowRight size={17}/></Button></div></DialogContent></Dialog>;}

export function EditProfileDialog({state,onClose,onSave}:{state:DemoState;onClose:()=>void;onSave:(name:string,bio:string)=>void}){
  const [name,setName]=useState(state.profileName),[bio,setBio]=useState(state.bio);
  return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="polis-dialog"><DialogHeader><DialogTitle>Make yourself at home.</DialogTitle><DialogDescription>Update your local demo profile.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(name.trim()){onSave(name.trim(),bio.trim());onClose();}}}><label className="field-label" htmlFor="profile-name">Name</label><input id="profile-name" value={name} onChange={e=>setName(e.target.value)} maxLength={40} required/><label className="field-label" htmlFor="profile-bio">A little about you</label><textarea id="profile-bio" value={bio} onChange={e=>setBio(e.target.value)} maxLength={160} rows={3}/><Button className="btn primary full" type="submit" disabled={!name.trim()}>Save profile<Check size={17}/></Button></form></DialogContent></Dialog>;
}
