"use client";
import {ArrowRight,ChevronRight,Bookmark,BookmarkCheck,BookOpen} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {items,itemById,kinds,type Kind,type CivicItem} from "@/lib/polis-data";
import {Avatar,AvatarStack,Score,EventRow,ItemRow,EmptyState,PageHeading,type ViewProps} from "./common";
import CommunityMap from "./community-map";

export function LocalRail({state,onOpen,onNavigate}:ViewProps){
  return <aside className="local-rail"><section><h2>Around the corner</h2><div className="mini-map-panel"><CommunityMap compact onSelect={onOpen} showFriends={state.showFriendRsvps} following={state.following}/><button className="map-link" onClick={()=>onNavigate("map")}>Explore the map<ChevronRight size={19}/></button></div></section><section className="week-section"><h2>This week</h2>{["housing-meeting","creek-cleanup"].map(id=><EventRow key={id} item={itemById[id]} state={state} onOpen={onOpen} compact/>)}</section><button className="passport-preview" onClick={()=>onNavigate("profile")}><BookOpen size={36} strokeWidth={1.3}/><span><strong>Your civic passport</strong><span>{state.rankings.length?"Your community story is taking shape.":"Your next chapter starts nearby."}</span></span><ChevronRight size={18}/></button><p className="demo-footnote">Illustrative demo · People, stories, scores, and events are samples. Changes stay on this device.</p></aside>;
}
export default function Discover({state,onOpen,onRank,onSave,onNavigate,category,onCategory,query}:{category:string;onCategory:(s:string)=>void;query:string}&ViewProps){
  const filtered=items.filter(item=>(category==="For you"||item.kind===category)&&(!query||(item.title+" "+item.topic+" "+item.subtitle).toLowerCase().includes(query.toLowerCase())));
  const heroRank=state.rankings.find(r=>r.itemId==="homes");
  const props={state,onOpen,onRank,onSave,onNavigate};
  function categoryContent(kind:Kind){
    if(!filtered.length)return <EmptyState title="No matches just yet" description="Try another topic or a shorter search."/>;
    return <div className="category-content"><div className="category-note">{kind==="News"?"News ratings reflect usefulness, not factual accuracy.":kind==="Politicians"?"Meet fictional candidates and explore their sample positions.":kind==="Events"?"Explore sample events. Your plans stay on this device.":"Explore the proposals and decide what matters to you."}</div>{filtered.map(item=>kind==="Events"?<EventRow key={item.id} item={item} state={state} onOpen={onOpen}/>:<ItemRow key={item.id} item={item} {...props}/>)}</div>;
  }
  return <div className="discovery-layout"><main className="feed-column" id="main-content" tabIndex={-1}><PageHeading title={query?"Find your next perspective.":"Your community, in focus."} description={query?'Results for “'+query+'”':"A little more informed. A lot more connected."}/>
    <Tabs value={category} onValueChange={onCategory} className="feed-tabs"><TabsList variant="line" className="category-tabs" aria-label="Discover categories">{["For you",...kinds].map(kind=><TabsTrigger value={kind} key={kind}>{kind}</TabsTrigger>)}</TabsList>
      <TabsContent value="For you">
        {query?<div className="search-results">{filtered.length?<><p className="category-note">{filtered.length} sample results</p>{filtered.map(item=><ItemRow key={item.id} item={item} {...props}/>)}</>:<EmptyState title="No matches just yet" description="Try housing, buses, parks, or a sample candidate’s name."/>}</div>:<>
          <article className="featured-story"><button className="feature-image-button" onClick={()=>onOpen(itemById.homes)} aria-label="Read about more homes downtown"><img className="feature-image" src="/images/community-street.webp" alt="Illustrative tree-lined college-town street with brick buildings" width="1536" height="1024"/><span className="image-caption">Illustrative photo</span></button><div className="feature-title-row"><div><span className="eyeline">Housing · Sample policy</span><button className="headline-button" onClick={()=>onOpen(itemById.homes)}><h2>More homes. More possibilities.</h2></button><p>A closer look at the proposal to bring more housing downtown.</p></div><button className="icon-btn feature-bookmark" aria-label={state.saved.includes("homes")?"Unsave downtown housing policy":"Save downtown housing policy"} onClick={()=>onSave("homes")}>{state.saved.includes("homes")?<BookmarkCheck size={21}/>:<Bookmark size={21}/>}</button></div><div className="feature-footer"><button className="friend-context" onClick={()=>onNavigate("friends")}><AvatarStack ids={["maya","oliver","sofia"]}/><span>Maya and 2 friends ranked this</span></button><button className="btn primary" onClick={()=>onRank(itemById.homes)}>{heroRank?"Edit your ranking":"Rank this policy"}</button><Score value={heroRank?.score??8.4} label={heroRank?"Your support":"Demo community support"}/></div></article>
          <section className="conversation"><div className="section-heading"><h2>The conversation around you</h2><button className="text-button" onClick={()=>onNavigate("friends")}>Friends<ArrowRight size={15}/></button></div><button className="activity-row" onClick={()=>onOpen(itemById.buses)}><Avatar id="maya"/><span><span><strong>Maya Chen</strong> ranked a policy</span><span className="activity-title">“Expanded evening bus service”</span><span className="metadata">Sample activity · Transportation</span></span><Score small value={9.1}/></button><button className="news-compact" onClick={()=>onOpen(itemById["parks-news"])}><span className="news-thumb parks"><BookOpen size={24}/></span><span><strong>A new chapter for the waterfront</strong><span>Polis demo newsroom · Sample explainer</span></span><ChevronRight size={18}/></button><button className="news-compact" onClick={()=>onOpen(itemById["housing-news"])}><img src="/images/community-street.webp" alt="" width="96" height="64"/><span><strong>What more homes downtown could mean</strong><span>Polis demo newsroom · Sample explainer</span></span><ChevronRight size={18}/></button></section>
          <section className="next-perspectives"><div className="section-heading"><h2>A few more perspectives</h2><button className="text-button" onClick={()=>onCategory("Politicians")}>Meet the candidates<ArrowRight size={15}/></button></div>{[itemById.school,itemById.priya].map(item=><ItemRow key={item.id} item={item} {...props}/>)}</section>
        </>}
      </TabsContent>
      {kinds.map(kind=><TabsContent value={kind} key={kind}>{category===kind&&categoryContent(kind)}</TabsContent>)}
    </Tabs>
  </main><LocalRail {...props}/></div>;
}
