export type Kind = "Policies" | "News" | "Politicians" | "Events";
export type View = "discover" | "map" | "rankings" | "friends" | "profile";
export type Audience = "Private" | "Friends" | "Public";
export type CivicItem = {
  id: string; kind: Kind; topic: string; title: string; subtitle: string;
  summary: string; details: string[]; considerations: string[];
  score: number; count: number; related: string[];
  source?: string; initials?: string; color?: string;
  event?: { day: string; month: string; weekday: string; time: string; place: string; type: string; x: number; y: number; friends: string[] };
};
export const kinds: Kind[] = ["Policies", "News", "Politicians", "Events"];
export const items: CivicItem[] = [
  {id:"homes",kind:"Policies",topic:"Housing",title:"More homes downtown",subtitle:"A proposal to allow more homes above downtown shops.",summary:"This fictional proposal would allow small apartment buildings and homes above shops in the downtown area. It explores how a growing college town could add housing near existing services.",details:["Allow buildings of up to five stories on selected downtown blocks.","Include below-market homes in larger developments.","Use existing sidewalks, bus routes, and utilities where capacity allows."],considerations:["Could additional homes improve availability while preserving neighborhood character?","What infrastructure investment would be needed, and who would fund it?"],score:8.4,count:128,related:["housing-news","housing-meeting","priya"]},
  {id:"buses",kind:"Policies",topic:"Transportation",title:"Expanded evening bus service",subtitle:"A later ride home, seven days a week.",summary:"This sample proposal adds evening buses between downtown, residential neighborhoods, and campus. The pilot would track ridership and operating costs before any permanent expansion.",details:["Add service until midnight on three sample routes.","Run a six-month pilot and publish ridership updates.","Evaluate access for workers, students, and residents without cars."],considerations:["Would enough people use the later service to justify the cost?","How should frequency be balanced against broader route coverage?"],score:9.1,count:96,related:["transit-news","transit-walk","daniel"]},
  {id:"parks",kind:"Policies",topic:"Public spaces",title:"A greener waterfront",subtitle:"More public paths, trees, and places to spend an afternoon.",summary:"This illustrative plan connects existing public spaces with an accessible walking path. It includes shade trees, benches, and a maintenance budget.",details:["Connect two sample waterfront paths.","Add step-free access and shaded seating.","Set aside an annual maintenance fund."],considerations:["How should the project balance recreation and habitat protection?","Which improvements should come first if funding is limited?"],score:8.8,count:74,related:["parks-news","creek-cleanup","elise"]},
  {id:"school",kind:"Policies",topic:"Education",title:"Open the library after hours",subtitle:"An evening space for studying, workshops, and community groups.",summary:"This sample policy would extend public library hours twice a week with staffed study spaces and bookable community rooms.",details:["Add two weekday evenings of staffed opening hours.","Offer free room bookings for local community groups.","Review attendance and staffing costs after one semester."],considerations:["How should additional staffing be funded?","Would expanded hours or additional daytime services help more residents?"],score:8.0,count:63,related:["library-forum","elise"]},
  {id:"housing-news",kind:"News",topic:"Housing",title:"What more homes downtown could mean",subtitle:"The questions behind a changing neighborhood.",summary:"In this sample explainer, a town weighs adding homes near shops and transit. The debate includes housing availability, infrastructure, affordability requirements, and the pace of change.",details:["A proposal is different from an approved or funded project.","Housing costs depend on several factors; no single policy guarantees lower rents.","Public meetings offer an opportunity to ask about implementation and trade-offs."],considerations:["Which claims would you want supporting evidence for?","Whose experience is missing from the discussion?"],score:8.7,count:85,source:"Polis demo newsroom",related:["homes","housing-meeting"]},
  {id:"transit-news",kind:"News",topic:"Transportation",title:"A later bus home: the case for an evening pilot",subtitle:"Frequency, funding, and who gets left at the last stop.",summary:"This original demonstration article lays out questions a community could ask before trialing later bus service. Its people, proposal, and reporting are fictional.",details:["A pilot could collect information about demand at different times.","Operating costs include drivers, maintenance, and fuel or electricity.","Useful evaluation would compare riders served with the alternatives."],considerations:["Which outcomes should determine whether the pilot continues?","How could the pilot reach people who do not currently ride the bus?"],score:8.5,count:52,source:"Polis demo newsroom",related:["buses","transit-walk"]},
  {id:"parks-news",kind:"News",topic:"Public spaces",title:"A new chapter for the waterfront",subtitle:"Making room for people and the places they share.",summary:"A fictional community considers an accessible waterfront connection. This sample story introduces the project, its potential benefits, and the questions residents might ask.",details:["Accessible paths can be planned alongside habitat restoration.","Ongoing maintenance matters as much as the initial construction budget.","Public feedback could help prioritize seating, shade, and access points."],considerations:["Who would use this space, and what would make it accessible?","How would the community measure whether the project was successful?"],score:8.9,count:41,source:"Polis demo newsroom",related:["parks","creek-cleanup"]},
  {id:"priya",kind:"Politicians",topic:"City council",title:"Priya Bennett",initials:"PB",color:"blue",subtitle:"Fictional council candidate · Housing & neighborhoods",summary:"Priya is a fictional candidate created for this demo. Her sample platform focuses on housing availability, walkable neighborhoods, and transparent project reviews.",details:["Supports allowing more homes near transit.","Proposes publishing clear milestones for public projects.","Favors testing small street improvements before permanent construction."],considerations:["Which parts of this sample platform do you support?","What experience or evidence would you want to assess before making a real voting decision?"],score:8.2,count:68,related:["homes","housing-meeting"]},
  {id:"daniel",kind:"Politicians",topic:"City council",title:"Daniel Reyes",initials:"DR",color:"orange",subtitle:"Fictional council candidate · Transportation & budgets",summary:"Daniel is a fictional candidate created for this demo. His sample platform centers on reliable transit, public budgeting, and evaluating new programs before expansion.",details:["Supports a measured pilot of evening bus service.","Proposes a resident-friendly city budget explainer.","Prioritizes maintaining existing infrastructure."],considerations:["How do you weigh new services against maintaining existing ones?","What information would help you evaluate this candidate's priorities?"],score:7.9,count:56,related:["buses","transit-walk"]},
  {id:"elise",kind:"Politicians",topic:"City council",title:"Elise Park",initials:"EP",color:"green",subtitle:"Fictional council candidate · Public spaces & learning",summary:"Elise is a fictional candidate created for this demo. Her sample platform focuses on public spaces, library access, and community participation.",details:["Supports extending library hours with a staffing plan.","Proposes improved access to public waterfront spaces.","Favors publishing plain-language meeting summaries."],considerations:["Which of these priorities would you put first?","How should a community fund and evaluate these programs?"],score:8.6,count:49,related:["school","parks","library-forum"]},
  {id:"housing-meeting",kind:"Events",topic:"Housing",title:"Downtown housing town hall",subtitle:"Bring your questions. Find a seat with friends.",summary:"A sample community conversation about a fictional downtown housing proposal. Explore how a news story, a policy ranking, and a plan to participate could come together.",details:["A short introduction to the sample proposal.","Small-group discussion and questions.","Step-free venue access in this demo scenario."],considerations:["This is a demonstration event, not a real booking.","Your RSVP is a plan saved on this device only."],score:8.6,count:24,related:["homes","housing-news"],event:{day:"12",month:"SEP",weekday:"Sat",time:"6:00–8:00 PM",place:"Downtown community room",type:"Town halls",x:48,y:57,friends:["maya","oliver","sofia"]}},
  {id:"creek-cleanup",kind:"Events",topic:"Environment",title:"Six Mile Creek cleanup",subtitle:"A little fresh air. A tangible difference.",summary:"A fictional neighborhood cleanup along a public creekside path. The demo shows how people could discover a local activity through friends.",details:["Meet the sample group at the trail entrance.","Gloves and bags would be provided in this scenario.","A short accessible route is included."],considerations:["This sample event is not scheduled in the real world.","An RSVP demonstrates planning; it does not verify attendance."],score:9.2,count:31,related:["parks","parks-news"],event:{day:"14",month:"SEP",weekday:"Mon",time:"9:00–11:00 AM",place:"Six Mile Creek trail entrance",type:"Volunteering",x:65,y:77,friends:["alex","maya"]}},
  {id:"transit-walk",kind:"Events",topic:"Transportation",title:"Walk & talk: a better bus ride",subtitle:"Explore the route and share your experience.",summary:"A sample community walk considering bus stops, access, and an illustrative evening-service proposal.",details:["An easy-paced, one-mile sample walk.","A conversation about access and waiting spaces.","Finish with a short discussion of service priorities."],considerations:["The route and event are illustrative.","No location is tracked or shared by this demo."],score:8.4,count:19,related:["buses","transit-news"],event:{day:"13",month:"SEP",weekday:"Sun",time:"3:00–4:30 PM",place:"Collegetown meeting point",type:"Meetups",x:79,y:38,friends:["oliver","sofia"]}},
  {id:"library-forum",kind:"Events",topic:"Education",title:"An open evening at the library",subtitle:"Help imagine a library with room for everyone.",summary:"A fictional open house for a sample library-hours proposal, with space for questions and community ideas.",details:["Tour a sample community room.","Discuss opening hours and activities.","Learn how a proposal could be refined."],considerations:["This is illustrative content, not an actual library event.","Plans are stored only in your browser."],score:8.1,count:17,related:["school","elise"],event:{day:"15",month:"SEP",weekday:"Tue",time:"5:30–7:00 PM",place:"Community library",type:"Town halls",x:38,y:35,friends:["alex"]}},
];
export const itemById = Object.fromEntries(items.map(item=>[item.id,item])) as Record<string,CivicItem>;
export const friends = [
  {id:"maya",name:"Maya Chen",initials:"MC",color:"rose",bio:"A better bus ride and a good public park.",neighborhood:"Downtown",ratings:{homes:8.8,buses:9.1,parks:8.6,"housing-news":8.5}},
  {id:"oliver",name:"Oliver Brooks",initials:"OB",color:"blue",bio:"Curious about how our city works.",neighborhood:"Collegetown",ratings:{homes:7.7,buses:8.7,school:8.9,priya:8.0}},
  {id:"sofia",name:"Sofia Rivera",initials:"SR",color:"orange",bio:"Following the ideas that shape our neighborhoods.",neighborhood:"Fall Creek",ratings:{homes:8.5,buses:8.9,parks:9.1,daniel:7.8}},
  {id:"alex",name:"Alex Morgan",initials:"AM",color:"green",bio:"Libraries, little adventures, and showing up.",neighborhood:"South Hill",ratings:{parks:9.3,school:9.0,elise:8.6,"parks-news":8.9}},
];
export const questions: Record<Kind,{title:string;low:string;high:string;label:string}> = {
  Policies:{title:"How strongly do you support this policy?",low:"Strongly oppose",high:"Strongly support",label:"Your support"},
  News:{title:"How useful was this story?",low:"Not useful",high:"Very useful",label:"Your usefulness rating"},
  Politicians:{title:"How strongly do you support this candidate?",low:"Low support",high:"High support",label:"Your support"},
  Events:{title:"How worthwhile was this event?",low:"Not worthwhile",high:"Highly recommend",label:"Your experience"},
};
export const singular: Record<Kind,string> = {Policies:"policy",News:"story",Politicians:"politician",Events:"event"};
