import type { CommunityEvent } from "./types.ts";
import { officialEvents } from "./official-events.ts";
import { verifiedCampusEvents } from "./verified-campus-events.ts";

// Sample listings let curators exercise a campus before organizer-verified
// occurrences are collected. Every record is marked `sample` and its copy says
// so; the source link is a general reference, not a listing for that date.
const checkedAt = "2026-09-26T13:00:00.000Z";
const sample = (
  e: Omit<CommunityEvent, "checkedAt" | "timezone" | "status" | "sample" | "imageUrl" | "costDetails" | "accessibility" | "registration" | "registrationUrl"> &
    Partial<CommunityEvent>,
): CommunityEvent => ({
  checkedAt,
  timezone: "America/New_York",
  status: "published",
  sample: true,
  imageUrl: "",
  costDetails: "",
  accessibility: "",
  registration: "",
  registrationUrl: "",
  ...e,
});
const gainesville = "https://www.gainesvillefl.gov/";
const uf = "https://www.ufl.edu/";

export const ufSampleEvents: CommunityEvent[] = [
  ...["2026-09-30", "2026-10-07", "2026-10-14"].map((day) =>
    sample({
      id: `uf-sample-union-market-${day}`,
      seriesId: "uf-sample-union-market",
      title: "Union Street Farmers Market",
      description: "Sample listing for the weekly downtown market of local produce, food and crafts. Confirm dates and hours with the organizer.",
      organizer: "Union Street Farmers Market",
      sourceUrl: gainesville,
      venue: "Bo Diddley Plaza",
      address: "Downtown Gainesville, FL",
      city: "Gainesville",
      latitude: 29.6515,
      longitude: -82.3244,
      startsAt: day + "T20:00:00.000Z",
      endsAt: day + "T23:00:00.000Z",
      category: "food_markets",
      cost: "free",
      issueId: "",
    }),
  ),
  sample({
    id: "uf-sample-org-fair-2026-09-30",
    seriesId: "uf-sample-org-fair",
    title: "Student organization fair",
    description: "Sample listing: student organizations table on the plaza to meet new members.",
    organizer: "UF student organizations",
    sourceUrl: uf,
    venue: "Plaza of the Americas",
    address: "University of Florida, Gainesville, FL",
    city: "Gainesville",
    latitude: 29.6498,
    longitude: -82.3426,
    startsAt: "2026-09-30T15:00:00.000Z",
    endsAt: "2026-09-30T19:00:00.000Z",
    category: "campus_life",
    cost: "free",
    issueId: "uf-student-voice",
  }),
  sample({
    id: "uf-sample-voting-info-2026-09-30",
    seriesId: "uf-sample-voting-info",
    title: "Voting information table",
    description: "Sample listing: nonpartisan volunteers share how to check registration and find a polling place. Confirm deadlines with the Supervisor of Elections.",
    organizer: "Nonpartisan student volunteers (sample)",
    sourceUrl: "https://registration.elections.myflorida.com/CheckVoterStatus",
    venue: "Turlington Plaza",
    address: "University of Florida, Gainesville, FL",
    city: "Gainesville",
    latitude: 29.6489,
    longitude: -82.3444,
    startsAt: "2026-09-30T14:00:00.000Z",
    endsAt: "2026-09-30T18:00:00.000Z",
    category: "politics",
    cost: "free",
    issueId: "",
  }),
  sample({
    id: "uf-sample-commission-2026-10-01",
    seriesId: "uf-sample-commission",
    title: "City Commission meeting",
    description: "Sample listing for a public City Commission meeting. Check the city's meeting calendar for the actual date, agenda and public-comment rules.",
    organizer: "City of Gainesville",
    sourceUrl: gainesville,
    venue: "City Hall auditorium",
    address: "200 E University Ave, Gainesville, FL",
    city: "Gainesville",
    latitude: 29.6521,
    longitude: -82.3236,
    startsAt: "2026-10-01T17:00:00.000Z",
    endsAt: "2026-10-01T21:00:00.000Z",
    category: "civic_meetings",
    cost: "free",
    issueId: "uf-housing",
  }),
  sample({
    id: "uf-sample-free-fridays-2026-10-02",
    seriesId: "uf-sample-free-fridays",
    title: "Free Friday concert",
    description: "Sample listing for an outdoor evening concert downtown.",
    organizer: "City of Gainesville",
    sourceUrl: gainesville,
    venue: "Bo Diddley Plaza",
    address: "Downtown Gainesville, FL",
    city: "Gainesville",
    latitude: 29.6512,
    longitude: -82.3249,
    startsAt: "2026-10-03T00:00:00.000Z",
    endsAt: "2026-10-03T02:00:00.000Z",
    category: "music",
    cost: "free",
    issueId: "",
  }),
  sample({
    id: "uf-sample-lake-alice-2026-10-03",
    seriesId: "uf-sample-lake-alice",
    title: "Lake Alice cleanup",
    description: "Sample listing for a volunteer morning picking up litter around the lake. Wear closed-toe shoes.",
    organizer: "Campus volunteers (sample)",
    sourceUrl: uf,
    venue: "Lake Alice",
    address: "University of Florida, Gainesville, FL",
    city: "Gainesville",
    latitude: 29.6431,
    longitude: -82.3612,
    startsAt: "2026-10-03T13:00:00.000Z",
    endsAt: "2026-10-03T15:00:00.000Z",
    category: "volunteering",
    cost: "free",
    issueId: "uf-climate",
  }),
  sample({
    id: "uf-sample-senate-2026-10-06",
    seriesId: "uf-sample-senate",
    title: "Student Senate meeting",
    description: "Sample listing for a Student Senate meeting. Check Student Government's posted schedule for the actual time and room.",
    organizer: "UF Student Government",
    sourceUrl: uf,
    venue: "Reitz Union",
    address: "University of Florida, Gainesville, FL",
    city: "Gainesville",
    latitude: 29.6461,
    longitude: -82.3481,
    startsAt: "2026-10-06T22:30:00.000Z",
    endsAt: "2026-10-07T00:30:00.000Z",
    category: "civic_meetings",
    cost: "free",
    issueId: "uf-student-voice",
  }),
  sample({
    id: "uf-sample-watch-party-2026-10-10",
    seriesId: "uf-sample-watch-party",
    title: "Away-game watch party",
    description: "Sample listing for a campus watch party on a football Saturday.",
    organizer: "Campus programming (sample)",
    sourceUrl: uf,
    venue: "Reitz Union",
    address: "University of Florida, Gainesville, FL",
    city: "Gainesville",
    latitude: 29.6465,
    longitude: -82.3475,
    startsAt: "2026-10-10T19:30:00.000Z",
    endsAt: "2026-10-10T23:00:00.000Z",
    category: "sports",
    cost: "free",
    issueId: "",
  }),
  sample({
    id: "uf-sample-depot-festival-2026-10-17",
    seriesId: "uf-sample-depot-festival",
    title: "Fall community festival",
    description: "Sample listing for an afternoon festival with local vendors and music in the park.",
    organizer: "Community organizers (sample)",
    sourceUrl: gainesville,
    venue: "Depot Park",
    address: "Gainesville, FL",
    city: "Gainesville",
    latitude: 29.6437,
    longitude: -82.319,
    startsAt: "2026-10-17T16:00:00.000Z",
    endsAt: "2026-10-17T21:00:00.000Z",
    category: "festivals_parades",
    cost: "free",
    issueId: "",
  }),
];

const ithaca = "https://www.cityofithacany.gov/";
export const cornellSampleEvents: CommunityEvent[] = [
  sample({
    id: "cu-sample-voting-info-2026-09-30",
    seriesId: "cu-sample-voting-info",
    title: "Voting information table",
    description: "Sample listing: nonpartisan volunteers share how to check registration and find a polling place. Confirm deadlines with the Board of Elections.",
    organizer: "Nonpartisan student volunteers (sample)",
    sourceUrl: "https://voterlookup.elections.ny.gov/",
    venue: "Ho Plaza",
    address: "Cornell University, Ithaca, NY",
    city: "Ithaca",
    latitude: 42.4468,
    longitude: -76.4848,
    startsAt: "2026-09-30T15:00:00.000Z",
    endsAt: "2026-09-30T19:00:00.000Z",
    category: "politics",
    cost: "free",
    issueId: "",
  }),
  sample({
    id: "cu-sample-sa-meeting-2026-10-01",
    seriesId: "cu-sample-sa-meeting",
    title: "Student Assembly meeting",
    description: "Sample listing for a Student Assembly meeting. Check the Assemblies' posted schedule for the actual time and room.",
    organizer: "Cornell Student Assembly",
    sourceUrl: "https://www.cornell.edu/",
    venue: "Willard Straight Hall",
    address: "Cornell University, Ithaca, NY",
    city: "Ithaca",
    latitude: 42.4463,
    longitude: -76.4857,
    startsAt: "2026-10-01T21:45:00.000Z",
    endsAt: "2026-10-01T23:45:00.000Z",
    category: "civic_meetings",
    cost: "free",
    issueId: "cu-student-voice",
  }),
  sample({
    id: "cu-sample-housing-forum-2026-10-06",
    seriesId: "cu-sample-housing-forum",
    title: "Collegetown housing forum",
    description: "Sample listing for a student-led conversation about rents, leases and new housing near campus.",
    organizer: "Student organizers (sample)",
    sourceUrl: ithaca,
    venue: "Collegetown",
    address: "Ithaca, NY",
    city: "Ithaca",
    latitude: 42.4421,
    longitude: -76.4847,
    startsAt: "2026-10-06T23:00:00.000Z",
    endsAt: "2026-10-07T00:30:00.000Z",
    category: "community",
    cost: "free",
    issueId: "housing",
  }),
  sample({
    id: "cu-sample-council-2026-10-07",
    seriesId: "cu-sample-council",
    title: "Common Council meeting",
    description: "Sample listing for a public Common Council meeting. Check the city calendar for the actual date, agenda and public-comment rules.",
    organizer: "City of Ithaca",
    sourceUrl: "https://www.cityofithacany.gov/Calendar.aspx",
    venue: "City Hall · Council Chambers",
    address: "108 E Green Street, Ithaca, NY 14850",
    city: "Ithaca",
    latitude: 42.4388,
    longitude: -76.4984,
    startsAt: "2026-10-07T22:00:00.000Z",
    endsAt: "2026-10-08T01:00:00.000Z",
    category: "civic_meetings",
    cost: "free",
    issueId: "housing",
  }),
  sample({
    id: "cu-sample-slope-concert-2026-10-09",
    seriesId: "cu-sample-slope-concert",
    title: "Friday evening concert on campus",
    description: "Sample listing for an outdoor student music night.",
    organizer: "Campus programming (sample)",
    sourceUrl: "https://www.cornell.edu/",
    venue: "Arts Quad",
    address: "Cornell University, Ithaca, NY",
    city: "Ithaca",
    latitude: 42.4491,
    longitude: -76.485,
    startsAt: "2026-10-09T23:00:00.000Z",
    endsAt: "2026-10-10T01:00:00.000Z",
    category: "music",
    cost: "free",
    issueId: "",
  }),
];

// Sample listings a curator may import to exercise a campus. The separate,
// organizer-checked Ithaca bundle remains its own import.
const samples: Record<string, CommunityEvent[]> = { ithaca: cornellSampleEvents, uf: ufSampleEvents };
export const sampleEventsFor = (communityId: string) => samples[communityId] ?? [];
// Everything importable into a community, checked listings first.
export function checkedEventsFor(communityId: string): CommunityEvent[] {
  const legacy = communityId === "ithaca" ? officialEvents.map(e => ({ ...e, scope: e.organizer === "Cornell Botanic Gardens" ? "campus" as const : "town" as const, campusId: e.organizer === "Cornell Botanic Gardens" ? "ithaca" : "", organizationName: e.organizer, imageCredit: e.imageUrl ? e.organizer : "", imageSourceUrl: e.sourceUrl, imageAlt: e.imageUrl ? e.title + " · organizer image" : "" })) : [];
  return [...legacy, ...verifiedCampusEvents.filter(e => e.city === (communityId === "ithaca" ? "Ithaca" : communityId === "uf" ? "Gainesville" : ""))];
}
// Curator import defaults to sourced records. Fiction remains a separate test bundle.
export const curatedEventsFor = checkedEventsFor;
