import type { CommunityEvent } from "./types.ts";

// Organizer sources checked September 26, 2026. No attendee information.
export const verifiedCampusEvents: CommunityEvent[] = [
  {
    "id": "cornell-csa-mid-autumn-2026",
    "seriesId": "cornell-csa-mid-autumn",
    "title": "CSA Mid-Autumn Festival 2026",
    "description": "Student performances, cultural booths, games, mooncakes, food and drinks; public description says everyone is welcome.",
    "organizer": "Chinese Students Association",
    "organizationName": "Chinese Students Association",
    "sourceUrl": "https://cornell.campusgroups.com/chinesestud/rsvp_boot?id=2310410",
    "checkedAt": "2026-09-26T20:00:00.000Z",
    "venue": "Ho Plaza",
    "address": "",
    "city": "Ithaca",
    "latitude": null,
    "longitude": null,
    "imageUrl": "https://cornell.campusgroups.com/upload/cornell/2020/r3_image_upload_1081324_IMG_0310PNG_9314351.jpeg",
    "imageSourceUrl": "https://cornell.campusgroups.com/chinesestud/rsvp_boot?id=2310410",
    "imageCredit": "Source: Cornell Chinese Students Association / CampusGroups; no individual creator credit found.",
    "imageAlt": "Red Chinese Students Association banner with the Cornell seal surrounded by zodiac animals",
    "imageNote": "Organizer banner used by the current event page, not a 2026-specific poster",
    "startsAt": "2026-10-03T00:00:00.000Z",
    "endsAt": "2026-10-03T04:00:00.000Z",
    "timezone": "America/New_York",
    "category": "festivals_parades",
    "cost": "free",
    "costDetails": "Free",
    "accessibility": "",
    "registration": "Free RSVP via event page.",
    "registrationUrl": "https://cornell.campusgroups.com/chinesestud/rsvp_boot?id=2310410",
    "issueId": "",
    "status": "published",
    "sample": false,
    "campusId": "ithaca",
    "scope": "campus"
  },
  {
    "id": "cornell-north-campus-food-show-2026",
    "seriesId": "cornell-north-campus-food-show",
    "title": "North Campus Retail Food Show",
    "description": "Cornell Dining vendors offer product samples and prizes for the Cornell community. Bring a reusable bag.",
    "organizer": "Cornell Dining / Student and Campus Life",
    "organizationName": "Cornell Dining / Student and Campus Life",
    "sourceUrl": "https://events.cornell.edu/event/north-campus-retail-food-show",
    "checkedAt": "2026-09-26T20:00:00.000Z",
    "venue": "Robert Purcell Community Center, rooms 103–105",
    "address": "",
    "city": "Ithaca",
    "latitude": 42.455906,
    "longitude": -76.477486,
    "imageUrl": "https://localist-images.azureedge.net/photos/53419188713259/huge/83fd9eca1a722f177dc487872e72f573fd790ce9.jpg",
    "imageSourceUrl": "https://events.cornell.edu/event/north-campus-retail-food-show",
    "imageCredit": "Source: Cornell Events / Cornell Dining; no individual photographer credit found.",
    "imageAlt": "Touchdown the Bear standing in front of the steps to Robert Purcell Community Center",
    "imageNote": "Official event-page photo",
    "startsAt": "2026-09-30T20:00:00.000Z",
    "endsAt": "2026-09-30T22:00:00.000Z",
    "timezone": "America/New_York",
    "category": "food_markets",
    "cost": "unknown",
    "costDetails": "",
    "accessibility": "",
    "registration": "",
    "registrationUrl": "",
    "issueId": "",
    "status": "published",
    "sample": false,
    "campusId": "ithaca",
    "scope": "campus"
  },
  {
    "id": "uf-soulfest-2026",
    "seriesId": "uf-soulfest",
    "title": "Soulfest",
    "description": "Multicultural dance, song and school-spirit showcase involving UF students and the Gainesville community.",
    "organizer": "UF Homecoming & Gator Growl",
    "organizationName": "UF Homecoming & Gator Growl",
    "sourceUrl": "https://www.gatorgrowl.org/soulfest",
    "checkedAt": "2026-09-26T20:00:00.000Z",
    "venue": "Reitz Union Grand Ballroom",
    "address": "",
    "city": "Gainesville",
    "latitude": null,
    "longitude": null,
    "imageUrl": "https://images.squarespace-cdn.com/content/v1/60d3966f052a022fe8263e20/f180efd2-d91c-4f30-a6ba-4d57c1b80635/HZ0A1522.JPG?format=1000w",
    "imageSourceUrl": "https://www.gatorgrowl.org/soulfest",
    "imageCredit": "Source: UF Homecoming & Gator Growl; no individual photographer credit found.",
    "imageAlt": "A Soulfest host holding a microphone under purple stage lighting",
    "imageNote": "Archival organizer photo from Soulfest gallery; do not label as a 2026 performance photo",
    "startsAt": "2026-10-01T22:00:00.000Z",
    "endsAt": null,
    "timezone": "America/New_York",
    "category": "arts_culture",
    "cost": "unknown",
    "costDetails": "",
    "accessibility": "",
    "registration": "",
    "registrationUrl": "",
    "issueId": "",
    "status": "published",
    "sample": false,
    "campusId": "uf",
    "scope": "campus"
  },
  {
    "id": "uf-gator-growl-2026",
    "seriesId": "uf-gator-growl",
    "title": "Gator Growl 2026",
    "description": "Homecoming entertainment headlined by Nikki Glaser, with co-hosts Laura Rutledge and Brandon Spikes.",
    "organizer": "UF Homecoming & Gator Growl",
    "organizationName": "UF Homecoming & Gator Growl",
    "sourceUrl": "https://www.oconnellcenter.ufl.edu/events/gator-growl-2026/",
    "checkedAt": "2026-09-26T20:00:00.000Z",
    "venue": "Stephen C. O’Connell Center",
    "address": "250 Gale Lemerand Drive, Gainesville, FL 32611",
    "city": "Gainesville",
    "latitude": null,
    "longitude": null,
    "imageUrl": "https://images.squarespace-cdn.com/content/v1/60d3966f052a022fe8263e20/7a345437-8fdf-4ba5-9a89-9ec171e4d4d0/nikki-glaser.jpg?format=1000w",
    "imageSourceUrl": "https://www.oconnellcenter.ufl.edu/events/gator-growl-2026/",
    "imageCredit": "Source: UF Homecoming & Gator Growl; no individual image creator credit found.",
    "imageAlt": "Gator Growl 2026 poster featuring Nikki Glaser, October 9 at the O’Connell Center, doors at 6 PM",
    "imageNote": "Official 2026 event poster",
    "startsAt": "2026-10-09T23:00:00.000Z",
    "endsAt": null,
    "timezone": "America/New_York",
    "category": "arts_culture",
    "cost": "paid",
    "costDetails": "Ticket purchase; exact current price not supplied on organizer/venue pages.",
    "accessibility": "Official venue page links accessibility information. Accessible tickets available through the University Box Office and Ticketmaster.",
    "registration": "Ticketmaster; organizer says open to UF and Santa Fe students, faculty, staff, alumni, university supporters and families.",
    "registrationUrl": "https://www.ticketmaster.com/event/220064ACF367A010",
    "issueId": "",
    "status": "published",
    "sample": false,
    "campusId": "uf",
    "scope": "campus"
  },
  {
    "id": "gainesville-looseys-trivia-2026-09-28",
    "seriesId": "gainesville-looseys-trivia-09-28",
    "title": "Loosey’s Trivia Night",
    "description": "Two rounds of ten questions with music bonus points and weekly prizes.",
    "organizer": "Loosey’s Downtown",
    "organizationName": "Loosey’s Downtown",
    "sourceUrl": "https://www.looseys.com/events/monday-trivia/",
    "checkedAt": "2026-09-26T20:00:00.000Z",
    "venue": "Loosey’s Downtown",
    "address": "120 SW 1st Ave, Gainesville, FL 32601",
    "city": "Gainesville",
    "latitude": null,
    "longitude": null,
    "imageUrl": "https://www.looseys.com/wp-content/uploads/2021/04/IMG_7977.png",
    "imageSourceUrl": "https://www.looseys.com/events/monday-trivia/",
    "imageCredit": "Source: Loosey’s Downtown; no individual artist credit found.",
    "imageAlt": "Collage poster for Monday Trivia Night: signups at 7, game at 7:30",
    "imageNote": "Current organizer-page recurring-series poster (alt text says 2025, but poster itself has no year)",
    "startsAt": "2026-09-28T23:30:00.000Z",
    "endsAt": "2026-09-29T02:00:00.000Z",
    "timezone": "America/New_York",
    "category": "arts_culture",
    "cost": "unknown",
    "costDetails": "",
    "accessibility": "",
    "registration": "Poster says signups at 7 PM; no online registration supplied.",
    "registrationUrl": "",
    "issueId": "",
    "status": "published",
    "sample": false,
    "campusId": "",
    "scope": "town"
  },
  {
    "id": "gainesville-free-fridays-2026-10-02",
    "seriesId": "gainesville-free-fridays-10-02",
    "title": "Free Fridays Concert Series — Elio Piedra",
    "description": "Free outdoor live music at Bo Diddley Plaza. October 2 lineup: Tu Fiesta Radio Presents Elio Piedra, rescheduled.",
    "organizer": "City of Gainesville Parks, Recreation and Cultural Affairs / Tu Fiesta Radio presents Elio Piedra",
    "organizationName": "City of Gainesville Parks, Recreation and Cultural Affairs / Tu Fiesta Radio presents Elio Piedra",
    "sourceUrl": "https://www.gainesvillefl.gov/Events-directory/PRCA-Events/Free-Fridays-Concert-Series",
    "checkedAt": "2026-09-26T20:00:00.000Z",
    "venue": "Bo Diddley Plaza",
    "address": "111 E. University Ave., Gainesville, FL 32601",
    "city": "Gainesville",
    "latitude": 29.6518056,
    "longitude": -82.3235373,
    "imageUrl": "https://www.gainesvillefl.gov/files/assets/public/v/1/parks-recreation-amp-cultural-affairs/images/free-fridays-web.png?w=1200",
    "imageSourceUrl": "https://www.gainesvillefl.gov/Events-directory/PRCA-Events/Free-Fridays-Concert-Series",
    "imageCredit": "Source: City of Gainesville Parks, Recreation and Cultural Affairs; no individual artist credit found.",
    "imageAlt": "Free Fridays Concert Series poster with a stylized guitar on a pink-to-purple gradient, Bo Diddley Plaza, Gainesville, Florida",
    "imageNote": "Official series poster",
    "startsAt": "2026-10-02T23:00:00.000Z",
    "endsAt": "2026-10-03T01:00:00.000Z",
    "timezone": "America/New_York",
    "category": "arts_culture",
    "cost": "free",
    "costDetails": "Free",
    "accessibility": "",
    "registration": "",
    "registrationUrl": "",
    "issueId": "",
    "status": "published",
    "sample": false,
    "campusId": "",
    "scope": "town"
  }
];
